# Makefile for JA4 Proxy

# ── Phony targets (alphabetical by group) ──────────────────────────────────
.PHONY: all help lint-help scan scan-all scan-container scan-local legacy-help dev-help
.PHONY: build rebuild clean
.PHONY: start start-monitoring start-scaled stop stop-clean status logs
.PHONY: dial ssh-tunnels flush-redis
.PHONY: attack-status top-attackers block-ja4 block-ip unblock-ip
.PHONY: fetch-db list-pending approve-all update-geoip check-geoip geoip-report geoip-monitor geoip-watch
.PHONY: test test-unit test-chaos test-adversarial test-calibrate test-docker test-component-suites
.PHONY: smoke-test smoke-docker smoke-k8s
.PHONY: lint lint-static lint-security lint-types lint-quality lint-coverage lint-pylint lint-semgrep lint-checkov
.PHONY: lint-docker lint-shell lint-yaml lint-lua lint-json lint-haproxy lint-helm lint-github-actions lint-ansible
.PHONY: lint-prom lint-alertmanager lint-secrets lint-deps lint-go-full lint-go-mod lint-makefiles lint-toml lint-markdown lint-spelling
.PHONY: lint-docs lint-phases link-check lint-all
.PHONY: scan scan-all scan-container scan-local scan-dockerfiles scan-images check-updates check-updates-container check-updates-local scan-first-party check-image-versions check-updates
.PHONY: go-build go-test go-lint go-start go-stop go-switch go-rollback go-parity check-scores parity-check
.PHONY: bench bench-quick bench-go bench-python
.PHONY: gdpr-delete
.PHONY: test-tap test-tap-live test-tap-perf
.PHONY: doc-health test-ratio
.PHONY: agent-up agent-down agent-status tunnel
.PHONY: management-build management-up management-down management-logs management-test management-shell
.PHONY: test-infra-monitoring test-infra-monitoring-integration test-provisioning
.PHONY: test-go-docker test-go-integration test-go-chaos test-go-perf test-go test-go-redis-tls
.PHONY: capture-fixtures capture-fixtures-browser go-build-ja4check deploy-poc deploy-enterprise measure-mttr

# Load machine-specific worker count (generated by: make test-calibrate)
-include .local/machine.mk
WORKERS ?= auto

# Normalise NAME= variable — accept Name= or name= as common typos
NAME ?= $(or $(Name),$(name))

# Default target
all: help

# ── Master help ───────────────────────────────────────────────────────────
help: lint-help scan-help legacy-help dev-help
	@echo ""
	@echo "JA4proxy — Available make targets"
	@echo ""
	@echo "── Quick reference (see sub-helps above for details) ──────────"
	@echo "  make lint-help  - Linting, scanning, security checks"
	@echo "  make scan-help  - Container image security scanning"
	@echo "  make legacy-help - Python-specific targets (legacy proxy)"
	@echo "  make dev-help   - Build, test, proxy, bench, docs, agents"
	@echo ""
	@echo "── Environment (.env) ────────────────────────────────────────"
	@echo "  BACKEND_HOST    - IP/hostname of your real backend server"
	@echo "  BACKEND_PORT    - Backend port (default 443)"
	@echo "  REDIS_PASSWORD  - Auto-generated on first start"
	@echo "  GRAFANA_PASSWORD- Auto-generated on first start"
	@echo "  JA4DB_API_KEY   - Optional ja4db.com API key"
	@echo ""
	@echo "── Incident Response (no restart needed) ─────────────────────"
	@echo "  attack-status   - Quick security snapshot"
	@echo "  top-attackers   - Top 10 fingerprints by traffic"
	@echo "  block-ja4 FP=.. - Blacklist JA4 fingerprint (instant TCP RST)"
	@echo "  block-ip IP=..  - Hard-block IP for 1 hour"
	@echo "  unblock-ip IP=. - Remove all blocks for IP"
	@echo "  flush-redis     - Reset bans/blocks/rates"
	@echo "  dial LEVEL=0-100- Set blocking dial via pubsub"
	@echo ""
	@echo "── Threat Intelligence ────────────────────────────────────────"
	@echo "  fetch-db        - Fetch malicious fingerprints from ja4db/FoxIO"
	@echo "  list-pending    - Show fingerprints awaiting admin approval"
	@echo "  approve-all     - Approve all pending fingerprints"
	@echo "  update-geoip    - Download latest IP2Location LITE DB (monthly)"
	@echo "  check-geoip     - Check age of current GeoIP database"
	@echo "  geoip-report    - Full blocking report"
	@echo "  geoip-monitor   - Auto-block attacking countries (run once)"
	@echo "  geoip-watch     - Auto-block attacking countries (continuous)"
	@echo ""

# ── Lint sub-help ────────────────────────────────────────────────────────
lint-help:
	@echo ""
	@echo "── Linting ───────────────────────────────────────────────────"
	@echo "  lint-static       - Python: mypy + bandit + ruff + pip-audit"
	@echo "  lint-go           - Go: go vet + go mod verify"
	@echo "  lint-shell        - shellcheck all .sh scripts"
	@echo "  lint-yaml         - yamllint config/ and deploy/monitoring/"
	@echo "  lint-docker       - hadolint + docker compose config check"
	@echo "  lint-prom         - promtool alert + recording rule validation"
	@echo "  lint-alertmanager - amtool Alertmanager config validation"
	@echo "  lint-secrets      - gitleaks scan of git history"
	@echo "  lint-deps         - run govulncheck/gosec (via container) + pip-audit"
	@echo "  lint-phases       - Validate manifest + phase doc integrity"
	@echo "  lint-all          - Run every linter in one shot"

# ── Scan sub-help ────────────────────────────────────────────────────────
scan-help:
	@echo ""
	@echo "── Security Scanning ─────────────────────────────────────────"
	@echo "  scan               - Run Go code security scan (containerized)"
	@echo "  scan-all           - Run all security scans (Go, Python, Images)"
	@echo "  scan-container     - Run govulncheck/gosec inside a container"
	@echo "  scan-local         - Run govulncheck/gosec locally"
	@echo ""
	@echo "── Container Scanning ────────────────────────────────────────"
	@echo "  scan-images        - Trivy scan of production images"
	@echo "  scan-dockerfiles   - Trivy scan of Dockerfiles (IaC)"
	@echo "  scan-first-party   - Trivy scan of 1st-party Python/Go deps"
	@echo "  check-image-versions - Check base image tags against Dockerfiles"
	@echo "  check-updates      - Check all deps (Docker, Go, Python, Node) for updates"

# ── Legacy (Python) sub-help ─────────────────────────────────────────────
legacy-help:
	@echo ""
	@echo "── Legacy Proxy (Python) ────────────────────────────────────"
	@echo "  go-start          - Start Python legacy proxy alongside Go"
	@echo "  go-stop           - Stop Python legacy proxy container"
	@echo "  go-switch         - Show instructions: confirm Go primary"
	@echo "  go-rollback       - Emergency: roll HAProxy back to Python"
	@echo "  go-parity         - Cross-language parity tests"
	@echo "  check-scores      - Audit scores against signal registry"
	@echo "  parity-check      - Live end-to-end decision parity"

# ── Dev sub-help ─────────────────────────────────────────────────────────
dev-help:
	@echo ""
	@echo "── Build ─────────────────────────────────────────────────────"
	@echo "  build             - Build Docker images (incremental)"
	@echo "  rebuild           - Wipe volumes/images, rebuild, start"
	@echo "  clean             - Stop + remove all containers/volumes"
	@echo ""
	@echo "── Startup / Shutdown ────────────────────────────────────────"
	@echo "  start             - Start full stack (POC + monitoring)"
	@echo "  start-monitoring  - Start monitoring stack only"
	@echo "  start-scaled      - Start 4-worker scaled + HAProxy"
	@echo "  stop              - Stop all services (keep Redis data)"
	@echo "  stop-clean        - Stop all + wipe volumes (fresh slate)"
	@echo "  status            - Show health + security state"
	@echo "  logs              - Stream proxy container logs"
	@echo "  ssh-tunnels       - Print SSH tunnel command for remote UI"
	@echo ""
	@echo "── Testing ───────────────────────────────────────────────────"
	@echo "  test              - Run all tests locally (fast, no Docker)"
	@echo "  test-unit         - Run unit tests only"
	@echo "  test-chaos        - Run chaos/resilience tests only"
	@echo "  test-adversarial  - Run adversarial/fuzz tests only"
	@echo "  test-calibrate    - Benchmark machine, store worker count"
	@echo "  test-docker       - Run tests inside Docker (CI env)"
	@echo "  test-component-suites - Run every component test suite"
	@echo "  smoke-test        - Quick sanity check"
	@echo "  smoke-docker      - Docker Compose lifecycle smoke test"
	@echo "  smoke-k8s         - Helm/kind smoke test (skips if absent)"
	@echo ""
	@echo "── Go Proxy ──────────────────────────────────────────────────"
	@echo "  go-build          - Build Go proxy binary to bin/ja4proxy"
	@echo "  go-test           - Run all Go unit tests"
	@echo "  go-lint           - Run go vet on Go code"
	@echo ""
	@echo "── Benchmarking ──────────────────────────────────────────────"
	@echo "  bench             - Full Go vs Python benchmark suite"
	@echo "  bench-quick       - Quick 10s/scenario (proxies running)"
	@echo "  bench-go          - Go proxy only benchmark"
	@echo "  bench-python      - Python proxy only benchmark"
	@echo "  ARGS=             - Extra flags e.g. make bench ARGS='--duration 120'"
	@echo ""
	@echo "── Documentation ─────────────────────────────────────────────"
	@echo "  lint-docs         - Validate doc frontmatter"
	@echo "  link-check        - Check internal Markdown links"
	@echo "  doc-health        - Run all doc quality checks"
	@echo "  test-ratio        - Show test-to-code ratio"
	@echo ""
	@echo "── Multi-Agent ───────────────────────────────────────────────"
	@echo "  agent-up NAME=..   - Start isolated agent env"
	@echo "  agent-down [NAME=] - Stop agent env"
	@echo "  agent-status       - List running agent environments"
	@echo "  tunnel NAME=..     - SSH tunnels for agent UIs"
	@echo ""
	@echo "  After agent-up, these auto-target active agent:"
	@echo "    stop  stop-clean  status  logs  health-check"
	@echo "    flush-redis  clean  rebuild"
	@echo "    management-up/down/logs/shell"
	@echo ""

# ── Startup / Shutdown ────────────────────────────────────────────────────────

# Start full stack (POC + monitoring)
start:
	@./scripts/start-all.sh

# Start monitoring stack only (Prometheus / Grafana / Loki)
start-monitoring:
	@./scripts/start-monitoring.sh

# Start scaled configuration with 4 workers and HAProxy (Phase 26d)
start-scaled:
	@echo "Starting JA4Proxy with 4-worker scaling..."
	@docker compose -f deploy/docker/docker-compose.poc.yml -f deploy/docker/docker-compose.scale.yml --env-file .env up -d
	@echo "✓ HAProxy load balancer started on port 443"
	@echo "✓ 4 worker processes started on ports 8080, 8083, 8084, 8085"
	@echo "✓ HAProxy stats available at http://localhost:8404/stats (admin/admin123)"

# Stop all services (keep Redis data)
stop:
	@./scripts/stop-all.sh

# Stop all services AND remove all volumes (fresh slate)
stop-clean:
	@./scripts/stop-all.sh --clean

# Show health of all services + security state
status:
	@./scripts/status.sh

# ── Multi-Agent ───────────────────────────────────────────────────────────────

# Start an isolated agent environment (auto-generates .env.<name> if missing).
# Writes .current-agent so subsequent commands default to this agent.
# Usage: make agent-up NAME=claude
agent-up:
	@[ -n "$(NAME)" ] || (echo "Usage: make agent-up NAME=<agent>  (agents: gemini|claude|ollama|mistral)"; exit 1)
	@[ -f ".env.$(NAME)" ] || (echo "→ No .env.$(NAME) found — generating..."; ./scripts/agent-env.sh $(NAME))
	docker compose -f deploy/docker/docker-compose.poc.yml --project-name ja4_$(NAME) --env-file .env.$(NAME) up -d
	@echo "$(NAME)" > .current-agent
	@echo "✓ Agent $(NAME) started (saved to .current-agent)"
	@IP=$$(grep '^AGENT_BIND_IP=' .env.$(NAME) | cut -d= -f2); \
	MGMT=$$(grep '^HOST_PORT_MANAGEMENT=' .env.$(NAME) | cut -d= -f2); MGMT=$${MGMT:-8090}; \
	ADMIN=$$(grep '^HOST_PORT_ADMIN_API=' .env.$(NAME) | cut -d= -f2); ADMIN=$${ADMIN:-8091}; \
	ANL=$$(grep '^HOST_PORT_ANALYTICS=' .env.$(NAME) | cut -d= -f2); ANL=$${ANL:-8080}; \
	echo "  Ingress:   https://$$IP:443"; \
	echo "  Analytics: http://$$IP:$$ANL"; \
	echo "  Management:http://$$IP:$$MGMT"; \
	echo "  Admin API: http://$$IP:$$ADMIN"; \
	echo "  Metrics:   http://$$IP:9090/metrics"
	@echo "  Admin:     ./scripts/ja4-admin.sh status  (uses .current-agent automatically)"
	@echo "  Tunnels:   make tunnel NAME=$(NAME) HOST=user@this-server"
	@echo ""
	@echo "Agent-aware targets (all read .current-agent automatically):"
	@echo "  make stop / stop-clean / status / logs / health-check"
	@echo "  make flush-redis / clean / rebuild"
	@echo "  make management-up/down/logs/shell"

# Stop an isolated agent environment.
# If NAME is not given, reads .current-agent (set by the last agent-up).
# Clears .current-agent if it matches the stopped agent.
# Usage: make agent-down NAME=claude  OR  make agent-down
agent-down:
	$(eval _NAME := $(or $(NAME),$(shell cat .current-agent 2>/dev/null)))
	@[ -n "$(_NAME)" ] || (echo "Usage: make agent-down NAME=<agent>  (or run make agent-up first to set .current-agent)"; exit 1)
	@[ -f ".env.$(_NAME)" ] || (echo "No .env.$(_NAME) — is agent $(_NAME) configured?"; exit 1)
	docker compose -f deploy/docker/docker-compose.poc.yml --project-name ja4_$(_NAME) --env-file .env.$(_NAME) down
	@if [ "$$(cat .current-agent 2>/dev/null)" = "$(_NAME)" ]; then rm -f .current-agent; echo "✓ Cleared .current-agent"; fi

# List all running agent environments and show which is current.
agent-status:
	@echo "Running ja4_* agent environments:"
	@docker compose ls 2>/dev/null | grep '^ja4_' || echo "  (none running)"
	@if [ -f .current-agent ]; then echo "Current (.current-agent): $$(cat .current-agent)"; fi

# ── Build ──────────────────────────────────────────────────────────────────────

# Build Docker images
build:
	@echo "Building Docker images (BuildKit enabled)..."
	DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 \
	docker compose -f deploy/docker/docker-compose.poc.yml --env-file .env build

# Run all tests locally in parallel (fast — no Docker required)
# Skips tests marked @pytest.mark.live_services (require Go/Python proxy + Redis stack)
test:
	@./scripts/run-local-tests.sh $(ARGS)

# Run full suite including live-service tests
# Requires: Go proxy + Python proxy + Redis running (see docs/phases/PHASE_15.md)
# Usage: make test-live   or   make test-live ARGS="-k test_ja4_parity"
test-live:
	@PYTEST_MARKS="" ./scripts/run-local-tests.sh $(ARGS)

# Run unit tests only
test-unit:
	@python3 -m pytest tests/unit/ -n $(WORKERS) --dist=loadfile --timeout=60 --tb=short $(ARGS)

# Run chaos/resilience tests only
test-chaos:
	@python3 -m pytest tests/chaos/ -n $(WORKERS) --dist=loadfile --timeout=60 --tb=short $(ARGS)

# Run adversarial/fuzz tests only (no parallelism — some are stateful)
test-adversarial:
	@python3 -m pytest tests/adversarial/ --timeout=60 --tb=short $(ARGS)

# Benchmark this machine and store worker count in .local/machine.mk
test-calibrate:
	@python3 scripts/detect_workers.py

# Run tests inside Docker (CI / clean environment)
test-docker:
	@./scripts/run-tests.sh

# Run quick smoke test
smoke-test:
	@./scripts/smoke-test.sh

# Run linting
lint:
	docker run --rm -v $(PWD):/app python:3.13-slim sh -c "cd /app && pip install black flake8 mypy bandit pytest-cov ruff && ruff check proxy.py security/ src/ && echo \"✓ Linting passed\""

# Security scanning with bandit (medium/high severity, skip B104 bind-all)
lint-security:
	@python3 -m bandit -r src/ proxy.py -ll --skip B104 && echo "  ✓ lint-security passed"

# Type checking with mypy (suppress output)
lint-types:
	docker run --rm -v $(PWD):/app python:3.14-slim sh -c "cd /app && pip install mypy && mypy proxy.py security/ src/ 2>/dev/null || echo 'Mypy warnings above, see baseline docs/reports/MYPY_BASELINE.md'"

# Phase 16f static analysis gates — runs locally (no Docker required).
# All three tools must pass cleanly; failures block the CI build.
#   mypy:     type-check src/ and proxy.py using mypy.ini baseline
#   bandit:   SAST scan, medium/high severity only (-ll), ignore B104 (bind 0.0.0.0 intentional)
#   ruff:     fast linter/formatter-check (replaces flake8/isort for new code)
#   pip-audit: CVE scan of requirements.txt; urllib3 CVEs acknowledged (transitive, tracked backlog)
lint-static:
	@echo "=== mypy: type checking ==="
	@python3 -m mypy src/ proxy.py && echo "  ✓ mypy passed"
	@echo ""
	@echo "=== bandit: SAST (medium/high) ==="
	@python3 -m bandit -r src/ proxy.py -ll -q --skip B104 && echo "  ✓ bandit passed"
	@echo ""
	@echo "=== ruff: linting ==="
	@python3 -m ruff check src/ proxy.py && echo "  ✓ ruff passed (tests advisory only)"
	@echo ""
	@echo "=== pip-audit: CVE dependency scan ==="
	@pip-audit -r requirements.txt \
	  --ignore-vuln CVE-2025-50181 \
	  --ignore-vuln CVE-2025-66418 \
	  --ignore-vuln CVE-2025-66471 \
	  --ignore-vuln CVE-2026-21441 \
	  --ignore-vuln CVE-2026-4539 \
	  && echo "  ✓ pip-audit passed (urllib3 CVEs + pygments ReDoS acknowledged — transitive deps, no fix available)"
	@echo ""
	@echo "✓ All static analysis gates passed"

# Code quality with flake8 (suppress output)
lint-quality:
	docker run --rm -v $(PWD):/app python:3.14-slim sh -c "cd /app && pip install flake8 && flake8 proxy.py security/ src/ 2>/dev/null || echo 'Flake8 warnings above, see baseline docs/QUICK_REFERENCE.md'"

# Coverage reporting with pytest-cov (Phase 16c gate: ≥80% all modules)
lint-coverage:
	python3 -m pytest tests/ --ignore=tests/integration/test_docker_stack.py \
		--cov=src --cov=proxy \
		--cov-fail-under=80 \
		--cov-report=term-missing \
		--cov-report=html:reports/coverage/html

# Lint Dockerfiles (hadolint) and validate docker-compose files (docker compose config).
# Ignored rules are consciously accepted — see .hadolint.yaml for rationale.
# deploy/docker/docker-compose.test.yml is the full Go test environment.
HADOLINT_IGNORE := --ignore DL3008 --ignore DL3013 --ignore DL3015 --ignore DL3018 --ignore DL3059
HADOLINT_DOCKERFILES := deploy/docker/Dockerfile deploy/docker/Dockerfile.admin deploy/docker/Dockerfile.management \
	deploy/docker/Dockerfile.mockbackend deploy/docker/Dockerfile.test \
	deploy/docker/Dockerfile.trafficgen deploy/docker/Dockerfile.go-proxy src/analytics/Dockerfile src/tarpit/Dockerfile \
	tests/docker/Dockerfile.python-proxy tests/docker/Dockerfile.recorder \
	tests/docker/Dockerfile.test-runner tests/docker/Dockerfile.tls-backend

lint-docker:
	@echo "=== hadolint: Dockerfiles ==="
	@for f in $(HADOLINT_DOCKERFILES); do \
		printf "  %-50s" "$$f"; \
		result=$$(docker run --rm -i hadolint/hadolint hadolint $(HADOLINT_IGNORE) --no-color - < "$$f" 2>&1); \
		if [ -n "$$result" ]; then echo "FAIL"; echo "$$result"; exit 1; fi; \
		echo "OK"; \
	done
	@echo ""
	@echo "=== docker compose config: compose files ==="
	@# Phase-202: the `:?` required-credential syntax in poc/monitoring compose
	@# files forces operators to supply real secrets. For `config --quiet` lint
	@# we inject harmless placeholders so the static validation still runs.
	@BACKEND_HOST=lint-placeholder REDIS_PASSWORD=lint-placeholder \
		MANAGEMENT_JWT_SECRET=lint-placeholder MANAGEMENT_ADMIN_USER=lint-placeholder MANAGEMENT_ADMIN_PASSWORD=lint-placeholder \
		docker compose -f deploy/docker/docker-compose.poc.yml --env-file .env config --quiet \
		&& echo "  deploy/docker/docker-compose.poc.yml                      OK"
	@BACKEND_HOST=lint-placeholder REDIS_PASSWORD=lint-placeholder \
		MANAGEMENT_JWT_SECRET=lint-placeholder MANAGEMENT_ADMIN_USER=lint-placeholder MANAGEMENT_ADMIN_PASSWORD=lint-placeholder \
		docker compose -f deploy/docker/docker-compose.poc.yml -f deploy/docker/docker-compose.python-legacy.yml config --quiet \
		&& echo "  deploy/docker/docker-compose.python-legacy.yml (overlay)  OK"
	@docker compose -f deploy/docker/docker-compose.test.yml config --quiet \
		&& echo "  deploy/docker/docker-compose.test.yml                     OK"
	@REDIS_PASSWORD=lint-placeholder GRAFANA_PASSWORD=lint-placeholder \
		HAPROXY_STATS_USER=lint-placeholder HAPROXY_STATS_PASSWORD=lint-placeholder \
		docker compose -f deploy/docker/docker-compose.monitoring.yml config --quiet \
		&& echo "  deploy/docker/docker-compose.monitoring.yml               OK"
	@BACKEND_HOST=lint-placeholder docker compose -f deploy/docker/docker-compose.prod.yml config --quiet \
		&& echo "  deploy/docker/docker-compose.prod.yml                     OK"
	@BACKEND_HOST=lint-placeholder REDIS_PASSWORD=lint-placeholder \
		MANAGEMENT_JWT_SECRET=lint-placeholder MANAGEMENT_ADMIN_USER=lint-placeholder MANAGEMENT_ADMIN_PASSWORD=lint-placeholder \
		docker compose -f deploy/docker/docker-compose.poc.yml -f deploy/docker/docker-compose.scale.yml config --quiet \
		&& echo "  deploy/docker/docker-compose.scale.yml (overlay)          OK"
	@echo ""
	@echo "✓ Docker lint passed"

# Lint shell scripts with shellcheck (error-level only; warnings are advisory).
# SC2154 suppressed: variables sourced from .env are referenced but not assigned in-script.
SHELL_SCRIPTS := $(shell find . -name "*.sh" -not -path "./.git/*" -not -path "./node_modules/*" -not -path "./.claude/*" | sort)
lint-shell:
	@echo "=== shellcheck: shell scripts ==="
	@fail=0; \
	for f in $(SHELL_SCRIPTS); do \
		printf "  %-60s" "$$f"; \
		result=$$(docker run --rm -i koalaman/shellcheck:stable \
			--severity=error --exclude=SC2154 - < "$$f" 2>/dev/null); \
		if [ -n "$$result" ]; then echo "FAIL"; echo "$$result"; fail=1; \
		else echo "OK"; fi; \
	done; \
	[ $$fail -eq 0 ] || exit 1
	@echo ""
	@echo "✓ Shell lint passed"

# Scan third-party Docker images for HIGH/CRITICAL CVEs (Trivy).
# Third-party image list for CVE scanning. Keep in sync with docs/DOCKER_IMAGES.md.
# Fails only on CRITICAL findings; HIGH findings are reported but non-blocking.
# Scans only pinned third-party images (not images we build ourselves — use scan-first-party for those).
# Covers images deployed in deploy/docker/docker-compose.prod.yml + deploy/docker/docker-compose.monitoring.yml.
# Keep versions here in sync with those compose files.
TRIVY_IMAGES := haproxy:2.8.24-alpine \
	redis/redis-stack:7.4.0-v8 \
	oliver006/redis_exporter:v1.84.0 \
	prom/prometheus:v3.12.0 \
	prom/alertmanager:v0.32.1 \
	prom/node-exporter:v1.11.1 \
	grafana/grafana:13.0.1-ubuntu \
	grafana/loki:3.7.2 \
	grafana/promtail:3.6.11

# Manifest consistency check — run before committing a phase close-out.
# Verifies: TODO.md + PROJECT_STATUS.md in sync with manifest.yaml,
#           every COMPLETE phase has a CHANGELOG entry,
#           every manifest phase appears in CLAUDE.md's phase table.
check-manifest:
	@python3 scripts/check_manifest.py

scan-images:
	@echo "=== Trivy: third-party image CVE scan (HIGH + CRITICAL) ==="
	@echo "    Fails on CRITICAL; HIGH findings are reported but advisory."
	@echo "    CVEs listed in .trivyignore are documented exceptions."
	@echo ""
	@fail=0; \
	for img in $(TRIVY_IMAGES); do \
		echo "  Scanning $$img ..."; \
		result=$$(docker run --rm -v "$(PWD):/scan:ro" aquasec/trivy:0.70.0 image \
			--severity HIGH,CRITICAL --exit-code 0 \
			--no-progress --scanners vuln \
			--ignorefile /scan/.trivyignore \
			--format table "$$img" 2>&1 | grep -E "CRITICAL|HIGH|Total:" || true); \
		critical=$$(echo "$$result" | grep -c "^│.*CRITICAL" || true); \
		echo "    $$result"; \
		[ "$$critical" -eq 0 ] || { echo "    ^^^ CRITICAL findings in $$img — update image version or add to .trivyignore"; fail=1; }; \
		echo ""; \
	done; \
	[ $$fail -eq 0 ] || { echo "✗ CRITICAL CVEs found — see .trivyignore for documented exceptions"; exit 1; }
	@echo "✓ Image scan complete"

# Trivy misconfiguration scan of Dockerfiles and compose files.
# Does NOT require building images — analyses file content only.
# Catches: running as root, missing HEALTHCHECK, ADD with URL, exposed secrets, missing no-new-privileges.
# Policy: HIGH + CRITICAL → exit 1 (we own these files; zero tolerance).
scan-dockerfiles:
	@echo "=== Trivy: Dockerfile/compose misconfiguration scan (HIGH + CRITICAL) ==="
	@echo "    Fails on HIGH or CRITICAL findings."
	@fail=0; \
	for f in deploy/docker/Dockerfile deploy/docker/Dockerfile.go-proxy deploy/docker/Dockerfile.management \
		 deploy/docker/Dockerfile.mockbackend deploy/docker/Dockerfile.admin deploy/docker/Dockerfile.test \
		 deploy/docker/Dockerfile.trafficgen deploy/docker/Dockerfile.cli \
		 deploy/docker/docker-compose.poc.yml deploy/docker/docker-compose.monitoring.yml \
		 deploy/docker/docker-compose.prod.yml deploy/docker/docker-compose.scale.yml \
		 deploy/docker/docker-compose.python-legacy.yml; do \
		if [ -f "$$f" ]; then \
			echo ""; \
			echo "  ── Scanning $$f ──"; \
			docker run --rm \
				-v "$(PWD):/scan:ro" \
				aquasec/trivy:0.70.0 config \
				--severity HIGH,CRITICAL --exit-code 1 \
				"/scan/$$f" || fail=1; \
		fi; \
	done; \
	[ $$fail -eq 0 ] || { echo ""; echo "✗ Dockerfile scan failed — fix HIGH/CRITICAL findings above"; exit 1; }
	@echo ""
	@echo "✓ All Dockerfiles and compose files passed"

# CVE scan of first-party images we build.
# Run 'make build' first to ensure images are current.
# Policy: CRITICAL → exit 1; HIGH → reported but advisory.
scan-first-party:
	@echo "=== Trivy: first-party image CVE scan (HIGH + CRITICAL) ==="
	@echo "    Run 'make build' first to ensure images are current."
	@echo "    Fails on CRITICAL; HIGH findings are reported but advisory."
	@echo ""
	@fail=0; \
	for img in ja4proxy:1.0.0 ja4proxy-analytics:1.0.0 ja4proxy-tarpit:1.0.0 ja4proxy-mockbackend:1.0.0 ja4proxy-test:1.0.0 ja4proxy-trafficgen:1.0.0; do \
		echo "  Scanning $$img ..."; \
		result=$$(docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
			aquasec/trivy:0.70.0 image --severity HIGH,CRITICAL --exit-code 0 \
			--no-progress --scanners vuln --format table "$$img" 2>&1 \
			| grep -E "CRITICAL|HIGH|Total:" || true); \
		critical=$$(echo "$$result" | grep -c "CRITICAL" || true); \
		echo "    $$result"; \
		[ "$$critical" -eq 0 ] || { echo "    ^^^ CRITICAL in $$img — update base image"; fail=1; }; \
		echo ""; \
	done; \
	[ $$fail -eq 0 ] || exit 1
	@echo "✓ First-party image scan complete"

# Detect :latest tags and version drift between compose files.
# Runs in < 5 seconds — no external calls, no Docker required.
check-image-versions:
	@python3 scripts/check_image_versions.py

# Lint YAML config and monitoring files with yamllint.
# Line-length disabled (long Prometheus expressions are unavoidable).
# See .yamllint.yaml for full config.
YAML_DIRS := config monitoring
lint-yaml:
	@echo "=== yamllint: config and monitoring YAML ==="
	@yamllint -c .yamllint.yaml $(YAML_DIRS) && echo "✓ YAML lint passed"

# Validate Prometheus alert and recording rule files with promtool.
# Uses the prometheus container so promtool version matches the deployed version.
PROM_RULES := /monitoring/prometheus/alerts.yml \
	/monitoring/prometheus/recording_rules.yml \
	/monitoring/alertmanager/rules/proxy.rules.yml \
	/monitoring/alertmanager/rules/redis.rules.yml \
	/monitoring/alertmanager/rules/security.rules.yml
lint-prom:
	@echo "=== promtool check rules: Prometheus alert + recording rules ==="
	@docker run --rm --entrypoint promtool \
		-v "$(PWD)/deploy/monitoring:/monitoring" \
		prom/prometheus:v2.48.0 \
		check rules $(PROM_RULES) \
		&& echo "✓ Prometheus rules valid"

# Check Python and Go dependencies for known CVEs.
# pip-audit scans requirements.txt; govulncheck scans go.mod.
lint-deps: scan-container
	@echo "=== pip-audit: Python dependency CVEs ==="
	@pip-audit -r requirements.txt --no-deps || true
	@pip-audit -r requirements-test.txt --no-deps || true
	@pip-audit -r requirements-analytics.txt --no-deps || true
	@echo "  (CVEs above are advisory — pinned versions may lag; update requirements.txt to remediate)"
	@echo ""
	@echo ""
	@echo "✓ Dependency scan complete"

# Scan git history for accidentally committed secrets (gitleaks).
# Scans committed files only — working-tree secrets are handled by .gitignore.
# False positives are suppressed in .gitleaks.toml with rationale.
lint-secrets:
	@echo "=== gitleaks: scan git history for secrets ==="
	@docker run --rm \
		-v "$(PWD):/repo" \
		zricethezav/gitleaks:latest detect \
		--source /repo --no-banner --config /repo/.gitleaks.toml \
		&& echo "✓ No secrets found in git history"

# Comprehensive Go linting with golangci-lint (errcheck, ineffassign, staticcheck, govet, unused).
# Uses the container's own Go — do not pass GOROOT. See .golangci.yaml for config and rationale.
lint-go-full:
	@echo "=== golangci-lint: Go code ==="
	@docker run --rm \
		-v "$(PWD):/app" -w /app \
		golangci/golangci-lint:latest \
		golangci-lint run --config .golangci.yaml ./... \
		&& echo "✓ Go lint passed"

# Lint the Redis Lua script with luacheck.
# KEYS, ARGV, and redis globals are declared in .luacheckrc (Redis runtime injects them).
LUACHECK_SCRIPTS := scripts/sliding_window.lua
lint-lua:
	@echo "=== luacheck: Lua/Redis scripts ==="
	@docker run --rm \
		-v "$(PWD):/repo" \
		pipelinecomponents/luacheck \
		luacheck --config /repo/.luacheckrc $(addprefix /repo/,$(LUACHECK_SCRIPTS)) \
		&& echo "✓ Lua lint passed"

# Validate JSON files: Grafana dashboards and API spec.
JSON_FILES := deploy/monitoring/grafana/dashboards/ja4proxy-overview.json \
	deploy/monitoring/grafana/dashboards/analytics.json \
	docs/api/openapi.json
lint-json:
	@echo "=== JSON syntax validation ==="
	@fail=0; \
	for f in $(JSON_FILES); do \
		[ -f "$$f" ] || continue; \
		printf "  %-60s" "$$f"; \
		if python3 -m json.tool "$$f" > /dev/null 2>&1; then echo "OK"; \
		else echo "FAIL"; fail=1; fi; \
	done; \
	[ $$fail -eq 0 ] || exit 1
	@echo "✓ JSON lint passed"

# Validate Alertmanager configuration with amtool.
# Uses the alertmanager container to match the deployed version.
lint-alertmanager:
	@echo "=== amtool check-config: Alertmanager ==="
	@docker run --rm \
		--entrypoint amtool \
		-v "$(PWD)/deploy/monitoring:/monitoring" \
		prom/alertmanager:v0.26.0 \
		check-config /monitoring/alertmanager/alertmanager.yml \
		&& echo "✓ Alertmanager config valid"

# Clean up (agent-aware: uses .current-agent if set)
clean:
	$(eval _AGENT := $(shell cat .current-agent 2>/dev/null))
	@echo "Cleaning up containers and volumes..."
	@if [ -n "$(_AGENT)" ]; then \
		docker compose -f deploy/docker/docker-compose.poc.yml --project-name ja4_$(_AGENT) --env-file .env.$(_AGENT) down -v --remove-orphans; \
	else \
		docker compose -f deploy/docker/docker-compose.poc.yml --env-file .env down -v --remove-orphans; \
	fi
	BACKEND_HOST=_ docker compose -f deploy/docker/docker-compose.prod.yml down -v --remove-orphans 2>/dev/null || true
	# Remove reports and cache directories, ignoring errors (e.g., from container-created files with restrictive permissions)
	rm -rf reports/ __pycache__/ .pytest_cache/ .mypy_cache/ 2>/dev/null || true

# Full clean rebuild from scratch — wipes volumes, removes built images, rebuilds, starts.
# If .current-agent is set (i.e. an agent stack is active), rebuilds and restarts that
# agent's stack.  Otherwise rebuilds and restarts the default ja4proxy stack.
rebuild:
	$(eval _AGENT := $(shell cat .current-agent 2>/dev/null))
	@echo "Stopping all services and wiping volumes..."
	@if [ -n "$(_AGENT)" ]; then \
		echo "  (active agent: $(_AGENT))"; \
		docker compose -f deploy/docker/docker-compose.poc.yml --project-name ja4_$(_AGENT) --env-file .env.$(_AGENT) down -v --remove-orphans --rmi local; \
	else \
		docker compose -f deploy/docker/docker-compose.poc.yml --env-file .env down -v --remove-orphans --rmi local; \
	fi
	docker compose -f deploy/docker/docker-compose.monitoring.yml down -v --remove-orphans --rmi local 2>/dev/null || true
	@echo "Rebuilding all images (no cache, but preserving apt/pip build caches)..."
	DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 \
	docker compose -f deploy/docker/docker-compose.poc.yml --env-file .env build --no-cache
	@echo "Starting full stack..."
	@if [ -n "$(_AGENT)" ]; then \
		docker compose -f deploy/docker/docker-compose.poc.yml --project-name ja4_$(_AGENT) --env-file .env.$(_AGENT) up -d; \
	else \
		./scripts/start-all.sh; \
	fi

# Deploy PoC environment
deploy-poc:
	@./scripts/start-poc.sh

# Deploy enterprise environment
deploy-enterprise:
	@echo "Running enterprise deployment script..."
	@sudo ./scripts/deploy.sh production

# Health checks (agent-aware: uses .current-agent if set)
health-check:
	$(eval _AGENT := $(shell cat .current-agent 2>/dev/null))
	@ENVFILE=$$([ -n "$(_AGENT)" ] && echo ".env.$(_AGENT)" || echo ".env"); \
	IP=$$(grep '^AGENT_BIND_IP=' "$$ENVFILE" 2>/dev/null | cut -d= -f2); IP=$${IP:-localhost}; \
	RPASS=$$(grep '^REDIS_PASSWORD=' "$$ENVFILE" 2>/dev/null | cut -d= -f2); RPASS=$${RPASS:-changeme}; \
	FLAGS=$$([ -n "$(_AGENT)" ] && echo "--project-name ja4_$(_AGENT) --env-file $$ENVFILE" || true); \
	echo "Running health checks ($$IP)..."; \
	curl -sf "http://$$IP:9090/metrics" > /dev/null && echo "✓ Proxy metrics OK" || echo "✗ Proxy metrics failed"; \
	curl -sk "https://$$IP:8443/api/health" > /dev/null && echo "✓ Backend OK" || echo "✗ Backend failed"; \
	docker compose -f deploy/docker/docker-compose.poc.yml --env-file .env $$FLAGS exec -T redis redis-cli -a "$$RPASS" ping > /dev/null 2>&1 && echo "✓ Redis OK" || echo "✗ Redis failed"

# View logs (agent-aware: uses .current-agent if set)
logs:
	$(eval _AGENT := $(shell cat .current-agent 2>/dev/null))
	@if [ -n "$(_AGENT)" ]; then \
		docker compose -f deploy/docker/docker-compose.poc.yml --project-name ja4_$(_AGENT) --env-file .env.$(_AGENT) logs -f proxy; \
	else \
		docker compose -f deploy/docker/docker-compose.poc.yml --env-file .env logs -f proxy; \
	fi

# Flush all transient security state from Redis (bans, blocks, rate windows, audit logs)
# Preserves ja4:whitelist and ja4:blacklist so config survives the flush.
# Agent-aware: uses .current-agent if set.
flush-redis:
	$(eval _AGENT := $(shell cat .current-agent 2>/dev/null))
	@ENVFILE=$$([ -n "$(_AGENT)" ] && echo ".env.$(_AGENT)" || echo ".env"); \
	REDIS_PASS=$$(grep '^REDIS_PASSWORD=' "$$ENVFILE" 2>/dev/null | cut -d= -f2); \
	if [ -z "$$REDIS_PASS" ]; then echo "✗ No REDIS_PASSWORD in $$ENVFILE"; exit 1; fi; \
	FLAGS=$$([ -n "$(_AGENT)" ] && echo "--project-name ja4_$(_AGENT) --env-file $$ENVFILE" || true); \
	echo "Flushing Redis security state$$([ -n "$(_AGENT)" ] && echo " (agent: $(_AGENT))")..."; \
	COUNT=$$(docker compose -f deploy/docker/docker-compose.poc.yml --env-file .env $$FLAGS exec -T redis redis-cli -a "$$REDIS_PASS" --no-auth-warning \
		EVAL "local n=0; \
		      for _,p in ipairs({'rate:*','banned:*','blocked:*','suspicious:*','enforcement:*','audit:*','repeat_block:*'}) do \
		        for _,k in ipairs(redis.call('keys',p)) do redis.call('del',k); n=n+1 end \
		      end; return n" 0 2>/dev/null); \
	echo "✓ Cleared $$COUNT keys (whitelist/blacklist preserved)"

# ── ja4db feed management ─────────────────────────────────────────────────────

# Fetch new malicious fingerprints from FoxIO GitHub / ja4db.com, queue for review
fetch-db:
	@./scripts/fetch-ja4db.sh

# Show fingerprints awaiting approval
list-pending:
	@./scripts/ja4-admin.sh list-pending

# Approve all pending fingerprints (prompts for confirmation)
approve-all:
	@./scripts/ja4-admin.sh approve-all

# ── GeoIP monitoring ───────────────────────────────────────────────────────────

# Full blocking report (countries, CIDRs, fingerprints, Prometheus summary)
geoip-report:
	@./scripts/ja4-admin.sh report

# Run the GeoIP monitor once — auto-blocks attacking countries, respects safe list
geoip-monitor:
	@./scripts/geoip-monitor.sh

# Run geoip-monitor in watch mode (loops every 60s, Ctrl-C to stop)
geoip-watch:
	@./scripts/geoip-monitor.sh --watch

# Download the latest IP2Location LITE country database (run monthly)
# Requires proxy restart after update: make stop && make start
update-geoip:
	@./scripts/update-geoip.sh

# Check how old the current GeoIP database is (no download)
check-geoip:
	@./scripts/update-geoip.sh --check

# ── Incident response shortcuts (wrappers for scripts/ja4-admin.sh) ──────────

# Quick security snapshot: active bans, block totals, top threats
attack-status:
	@./scripts/ja4-admin.sh status

# Top 10 fingerprints by traffic (red = blocked, green = allowed)
top-attackers:
	@./scripts/ja4-admin.sh top 10

# Blacklist a JA4 fingerprint (instant TCP RST, permanent)
# Usage: make block-ja4 FP=t13d190900_9dc949149365_97f8aa674fd9
block-ja4:
	@[ -n "$(FP)" ] || (echo "Usage: make block-ja4 FP=<fingerprint>"; exit 1)
	@./scripts/ja4-admin.sh block-ja4 $(FP)

# Hard-block an IP for 1 hour
# Usage: make block-ip IP=203.0.113.42
block-ip:
	@[ -n "$(IP)" ] || (echo "Usage: make block-ip IP=<address>"; exit 1)
	@./scripts/ja4-admin.sh block-ip $(IP) 3600

# Remove all blocks/bans for an IP
# Usage: make unblock-ip IP=203.0.113.42
unblock-ip:
	@[ -n "$(IP)" ] || (echo "Usage: make unblock-ip IP=<address>"; exit 1)
	@./scripts/ja4-admin.sh unblock-ip $(IP)

# Run performance tests
perf-test:
	@echo "Starting performance tests..."
	@echo "Note: This requires services to be running (make deploy-poc)"
	docker compose -f deploy/docker/docker-compose.poc.yml --env-file .env run --rm test locust -f /app/performance/locust_tests.py --host http://proxy:8080 --users 100 --spawn-rate 10 --run-time 5m --headless

# ── Configuration ─────────────────────────────────────────────────────────────

# Set the blocking dial (0 = monitor only, 100 = full blocking)
# Usage: make dial LEVEL=50
dial:
	@[ -n "$(LEVEL)" ] || (echo "Usage: make dial LEVEL=<0-100>"; exit 1)
	@python3 scripts/set_dial.py $(LEVEL)

# ── Operations ────────────────────────────────────────────────────────────────

# Print SSH tunnel command for the default (non-agent) stack.
# For agent stacks use: make tunnel NAME=<agent> [HOST=user@server]
ssh-tunnels:
	@echo ""
	@echo "NOTE: For agent stacks use: make tunnel NAME=<agent> HOST=user@server"
	@echo ""
	@echo "Default stack — run this on your laptop:"
	@echo ""
	@echo "  ssh -L 9091:localhost:9091 -L 9093:localhost:9093 -L 8404:localhost:8404 USER@HOST"
	@echo ""
	@echo "Then browse to:"
	@echo "  http://localhost:9091  — Prometheus"
	@echo "  http://localhost:9093  — Alertmanager"
	@echo "  http://localhost:8404/stats  — HAProxy stats"
	@echo "  http://localhost:3001  — Grafana"
	@echo ""

# ── Proxy Operations ──────────────────────────────────────────────────────────

# Prefer snap Go if present (local dev), else fall back to env/system GOROOT.
GOROOT := $(shell if [ -d /snap/go/current ]; then echo /snap/go/current; elif [ -n "$$GOROOT" ]; then echo "$$GOROOT"; else go env GOROOT 2>/dev/null; fi)
GO     := GOROOT=$(GOROOT) go

# Build the Go proxy binary into bin/ja4proxy
go-build:
	@echo "Building Go proxy..."
	@mkdir -p bin
	$(GO) build -o bin/ja4proxy ./cmd/proxy
	@echo "✓ bin/ja4proxy"

# Run all Go unit tests
go-test:
	$(GO) test ./... -count=1

# Run go vet (static analysis)
go-lint:
	$(GO) vet ./...

# Audit Python and Go signal scores against registry (Phase 65)
check-scores:
	@python3 scripts/check-signal-scores.py

# Live end-to-end decision parity verification (Phase 65)
parity-check:
	@python3 scripts/parity-check.py

# ── Security Scans ────────────────────────────────────────────────────────────

.PHONY: scan-container
scan-container:
	@# JA4proxy-2026-0010: ensure scan target returns 0 even if gosec finds issues
	@docker build -q -t ja4proxy-security-scan -f deploy/docker/security-scan/Dockerfile .

.PHONY: scan-local
scan-local:
	@(gosec -fmt=text -exclude-dir=.claude ./... || true)

.PHONY: scan
scan: scan-container

.PHONY: scan-all
scan-all: scan-container scan-dockerfiles scan-first-party scan-images
	@echo "✓ All scans passed"

# Analyze Docker containers and dependencies for version discrepancies
.PHONY: check-updates-container
check-updates-container:
	@echo "=== Containerized Update Check (Go, Python, Docker, Node) ==="
	@docker build -q -t ja4proxy-update-checker -f deploy/docker/update-checker/Dockerfile .
	@docker run --rm -v "$(PWD):/app" ja4proxy-update-checker

.PHONY: check-updates-local
check-updates-local:
	@echo "=== Local Update Check (Go, Python, Docker, Node) ==="
	@python3 scripts/check_updates.py

check-updates: check-updates-container

# Start Python legacy proxy alongside the Go proxy for parity comparison.
# Both proxies share the same Redis instance.
# Go proxy (primary): host port 8081 / metrics 9090
# Python proxy (legacy): host port 8083 / metrics 9094
go-start:
	@echo "Starting Python legacy proxy (port 8083) for parity comparison..."
	docker compose -f deploy/docker/docker-compose.poc.yml -f deploy/docker/docker-compose.python-legacy.yml --env-file .env up -d python-proxy
	@echo ""
	@echo "  Go proxy (primary): http://localhost:8081"
	@echo "  Go metrics/health:  http://localhost:9090/health"
	@echo "  Python proxy:       http://localhost:8083 (legacy, parity only)"
	@echo ""
	@echo "Run 'make go-parity' after 60s to validate decision parity."

# Stop Python legacy proxy (Go proxy unaffected)
go-stop:
	docker compose -f deploy/docker/docker-compose.poc.yml -f deploy/docker/docker-compose.python-legacy.yml --env-file .env stop python-proxy

# Confirm Go proxy is HAProxy primary (Go is the default — verify config is correct).
# See docs/runbooks/go_proxy_migration.md for background.
go-switch:
	@echo "Go proxy is the production default. Confirm HAProxy config points to the proxy service:"
	@echo ""
	@echo "  backend ja4proxy"
	@echo "      server go-proxy proxy:8080 check"
	@echo ""
	@echo "Then reload HAProxy if needed:"
	@echo "  docker compose exec haproxy haproxy -sf \$$(cat /var/run/haproxy.pid)"

# Emergency rollback: switch HAProxy to Python legacy proxy.
# Prerequisites: Python proxy must be running (make go-start).
go-rollback:
	@echo "EMERGENCY ROLLBACK — switching HAProxy to Python legacy proxy..."
	@echo ""
	@echo "Start Python proxy first (if not already running): make go-start"
	@echo ""
	@echo "Update HAProxy config to:"
	@echo "  backend ja4proxy"
	@echo "      server python-proxy python-proxy:8080 check"
	@echo ""
	@echo "Then reload HAProxy:"
	@echo "  docker compose exec haproxy haproxy -sf \$$(cat /var/run/haproxy.pid)"
	@echo ""
	@echo "Rollback complete. Run 'make go-switch' to restore Go proxy when ready."

# Run cross-language parity tests.
# Both proxies must be running: Python on :8080, Go on :8082.
go-parity:
	python3 -m pytest tests/integration/test_go_python_parity.py -v

# ── Docker test harness ────────────────────────────────────────────────────────

# Generate ClientHello fixtures (curl + openssl + synthetic)
capture-fixtures:
	@bash scripts/generate_fixtures.sh

# Build ja4check utility (reads .bin file, prints JA4 fingerprint)
go-build-ja4check:
	@echo "Building ja4check..."
	@mkdir -p bin
	$(GO) build -o bin/ja4check ./cmd/ja4check
	@echo "✓ bin/ja4check"

# Run Go integration tests inside Docker (full test harness, self-contained)
test-go-docker:
	@echo "Starting Go proxy test stack..."
	docker compose -f deploy/docker/docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from test-runner test-runner

# Run Go integration tests locally (requires Go proxy running on GO_PROXY_PORT)
test-go-integration:
	python3 -m pytest tests/integration/test_go_python_parity.py -v

# Run Go chaos tests locally (requires Go proxy running on GO_PROXY_PORT)
test-go-chaos:
	python3 -m pytest tests/chaos/test_go_proxy_chaos.py -v

# Run Go performance benchmarks locally (requires Go proxy running on GO_PROXY_PORT)
test-go-perf:
	python3 -m pytest tests/performance/test_bench_go_proxy.py -v -s

# Run all Go tests: build binaries, generate fixtures, then run test suite
test-go:
	$(MAKE) go-build
	$(MAKE) go-build-ja4check
	$(MAKE) capture-fixtures
	python3 -m pytest \
	  tests/integration/test_go_python_parity.py \
	  tests/chaos/test_go_proxy_chaos.py \
	  tests/performance/test_bench_go_proxy.py \
	  -v --tb=short

# Phase 201: smoke-test the Go Redis client against a real TLS-terminated Redis.
# Generates a self-signed cert, brings up the redis-tls compose overlay, runs the
# in-package TLS unit suite (which dials real TLS listeners via the harness),
# then tears down. Real TLS handshake; no shortcuts.
test-go-redis-tls:
	@bash deploy/docker/redis-tls/generate-certs.sh
	@docker compose -f deploy/docker/docker-compose.redis-tls.yml up -d --wait
	@trap 'docker compose -f deploy/docker/docker-compose.redis-tls.yml down -v' EXIT; \
	  GOROOT=$${GOROOT:-/snap/go/current} go test -race -count=1 ./internal/redis/... -run 'TLS|HealthCheck'

# ── Comparative benchmark: Go vs Python ──────────────────────────────────────

# Full benchmark suite (Go proxy, all scenarios).
# Starts services via Docker if not already running.
# Usage: make bench
#        make bench ARGS="--quick"
#        make bench ARGS="--scenarios peak_throughput,sustained_load --duration-long 60"
#        make bench ARGS="--proxy python"  # legacy Python proxy
bench:
	@./scripts/benchmark-go-python.sh $(ARGS)

# Quick sanity benchmark (10 s per scenario, 16 threads).
# Assumes proxies already running (--no-docker).
bench-quick:
	@./scripts/benchmark-go-python.sh --quick --no-docker $(ARGS)

# Go proxy only (default).
bench-go:
	@./scripts/benchmark-go-python.sh --proxy go $(ARGS)

# Legacy: Python proxy only (deprecated).
bench-python:
	@./scripts/benchmark-go-python.sh --proxy python $(ARGS)

# Capture browser-specific ClientHello fixtures (requires Docker + recorder service)
capture-fixtures-browser:
	docker compose -f deploy/docker/docker-compose.test.yml run --rm browser \
	  python3 scripts/generate_fixtures_browser.py --recorder-host recorder

# ── Docs ──────────────────────────────────────────────────────────────────────

# Check all docs have frontmatter and aren't stale
lint-docs:
	@echo "Checking documentation frontmatter..."
	@python3 scripts/check_doc_frontmatter.py

# Validate phase doc/manifest consistency (filename numbers, action_plan paths, statuses)
lint-phases:
	@python3 scripts/lint-phases.py

# Check all internal Markdown links are valid
link-check:
	@echo "Checking internal documentation links..."
	@find docs/ -name '*.md' | xargs markdown-link-check --config .mlc.json

# Verify no references to paths that have been moved or deleted (Phase 205).
# Only flags a path if the source directory/file no longer exists at root — so this
# target is safe to run before AND after the moves.  Before: all paths exist → pass.
# After: moved paths are gone → any remaining references are dangling → fail.
# Excludes historical phase docs and CHANGELOG (they record what was true at the time).
# Splunk container relocation
MOVED_PATHS := \
  deploy/docker/ ha-config/ deploy/monitoring/ ssl/ secrets/ integrations/ \
  performance/ test-content/ geoip/ tarpit/ ebpf/ memory/ \
  Dockerfile-cli Jenkinsfile.ja4proxy-policy \
  requirements-test.txt requirements-analytics.txt

check-paths:
	@echo "Checking for dangling path references..."
	@rc=0; \
	for old in $(MOVED_PATHS); do \
	  if [ -e "$$old" ]; then continue; fi; \
	  hits=$$(git grep -lF "$$old" \
	    -- ':!docs/phases/PHASE_*' ':!CHANGELOG.md' ':!docs/phases/*_review.md' \
	    2>/dev/null | wc -l); \
	  if [ "$$hits" -gt 0 ]; then \
	    echo "DANGLING: $$old  ($$hits files)"; \
	    git grep -lF "$$old" \
	      -- ':!docs/phases/PHASE_*' ':!CHANGELOG.md' ':!docs/phases/*_review.md'; \
	    rc=1; \
	  fi; \
	done; \
	if [ "$$rc" -eq 0 ]; then echo "✓ No dangling path references found"; fi; \
	exit $$rc

# Run all documentation quality checks
doc-health:
	@make lint-phases lint-docs link-check check-paths

# Show current test-to-code ratio
test-ratio:
	@echo "Calculating test-to-code ratio..."
	@python3 scripts/test_ratio.py

# ── TAP mode test targets ─────────────────────────────────────────────────────

# Run all TAP mode unit/chaos/corpus tests (parallel, no live capture required).
test-tap:
	@python3 -m pytest tests/tap/ tests/unit/tap/ tests/chaos/test_tap_enforcement_resilience.py tests/chaos/test_tap_export_resilience.py -n $(WORKERS) --dist=loadfile --timeout=60 --tb=short $(ARGS)

# Run TAP integration tests that require a live capture interface.
# Usage: make test-tap-live INTERFACE=eth1
test-tap-live:
	@[ -n "$(INTERFACE)" ] || (echo "Usage: make test-tap-live INTERFACE=eth1"; exit 1)
	@sudo python3 -m pytest tests/tap/integration/ --timeout=120 -k requires_tap_interface -v $(ARGS)

# Run TAP throughput benchmark.
# Usage: make test-tap-perf                        (synthetic, 200k packets)
#        make test-tap-perf ARGS="--packets 1000000"
#        make test-tap-perf ARGS="--mode pcap --pcap tests/pcap_corpus/chrome_tls13.pcap"
test-tap-perf:
	@python3 scripts/tap_benchmark.py $(ARGS)

# Delete all Redis data associated with a specific IP (GDPR right to erasure).
# Usage: make gdpr-delete IP=1.2.3.4
gdpr-delete:
	@[ -n "$(IP)" ] || (echo "Usage: make gdpr-delete IP=1.2.3.4"; exit 1)
	@python3 scripts/gdpr_delete.py --ip $(IP) $(if $(DRY_RUN),--dry-run,)

## ── Management UI ────────────────────────────────────────────────────────────
management-build:
	DOCKER_BUILDKIT=1 docker build -f deploy/docker/Dockerfile.management -t ja4proxy-management:1.0.0 .

management-up: management-build
	$(eval _AGENT := $(shell cat .current-agent 2>/dev/null))
	@if [ -n "$(_AGENT)" ]; then \
		docker compose -f deploy/docker/docker-compose.poc.yml --project-name ja4_$(_AGENT) --env-file .env.$(_AGENT) up -d management; \
	else \
		docker compose -f deploy/docker/docker-compose.poc.yml --env-file .env up -d management; \
	fi

management-down:
	$(eval _AGENT := $(shell cat .current-agent 2>/dev/null))
	@if [ -n "$(_AGENT)" ]; then \
		docker compose -f deploy/docker/docker-compose.poc.yml --project-name ja4_$(_AGENT) --env-file .env.$(_AGENT) stop management; \
	else \
		docker compose -f deploy/docker/docker-compose.poc.yml --env-file .env stop management; \
	fi

management-logs:
	$(eval _AGENT := $(shell cat .current-agent 2>/dev/null))
	@if [ -n "$(_AGENT)" ]; then \
		docker compose -f deploy/docker/docker-compose.poc.yml --project-name ja4_$(_AGENT) --env-file .env.$(_AGENT) logs -f management; \
	else \
		docker compose -f deploy/docker/docker-compose.poc.yml --env-file .env logs -f management; \
	fi

management-test:
	export PYTHONPATH=$(PYTHONPATH):. && python3 -m pytest management/tests/ -v

management-shell:
	$(eval _AGENT := $(shell cat .current-agent 2>/dev/null))
	@if [ -n "$(_AGENT)" ]; then \
		docker compose -f deploy/docker/docker-compose.poc.yml --project-name ja4_$(_AGENT) --env-file .env.$(_AGENT) exec management /bin/sh; \
	else \
		docker compose -f deploy/docker/docker-compose.poc.yml --env-file .env exec management /bin/sh; \
	fi


## Management UI backend API targets
test-mgmt-api:
	export PYTHONPATH=$(PYTHONPATH):. && python3 -m pytest management/tests/ -v

test-mgmt-api-unit:
	export PYTHONPATH=$(PYTHONPATH):. && python3 -m pytest management/tests/test_auth.py management/tests/test_dial.py management/tests/test_lists.py management/tests/test_bans.py management/tests/test_health.py management/tests/test_config_ops.py management/tests/test_audit.py -v

test-mgmt-api-events:
	export PYTHONPATH=$(PYTHONPATH):. && python3 -m pytest management/tests/test_events.py -v

## ── Remote access tunnels ────────────────────────────────────────────────────
# Print the SSH tunnel command for accessing a named agent's UIs from a remote
# machine (e.g. a Chromebook).
#
# Usage:
#   make tunnel NAME=claude4                  — print the ssh command
#   make tunnel NAME=claude4 HOST=me@server   — print AND open the tunnel
#
# The command forwards all per-agent ports (bound to AGENT_BIND_IP) plus the
# shared monitoring stack (Grafana, Prometheus) to localhost.
tunnel:
	@[ -n "$(NAME)" ] || (echo "Usage: make tunnel NAME=<agent> [HOST=user@server]"; exit 1)
	@[ -f ".env.$(NAME)" ] || (echo "No .env.$(NAME) found. Run: make agent-up NAME=$(NAME)"; exit 1)
	@bash -c ' \
		IP=$$(grep "^AGENT_BIND_IP=" .env.$(NAME) | cut -d= -f2); \
		MGMT=$$(grep "^HOST_PORT_MANAGEMENT=" .env.$(NAME) | cut -d= -f2); MGMT=$${MGMT:-8090}; \
		ADMIN=$$(grep "^HOST_PORT_ADMIN_API=" .env.$(NAME) | cut -d= -f2); ADMIN=$${ADMIN:-8091}; \
		ANL=$$(grep "^HOST_PORT_ANALYTICS=" .env.$(NAME) | cut -d= -f2); ANL=$${ANL:-8080}; \
		echo ""; \
		echo "Agent: $(NAME)  |  IP: $$IP"; \
		echo ""; \
		echo "Run this in a NEW terminal on your Chromebook:"; \
		echo ""; \
		if [ -n "$(HOST)" ]; then SERVER="$(HOST)"; else SERVER="USER@YOUR-SERVER"; fi; \
		echo "  ssh -N \\"; \
		echo "    -L $${MGMT}:$${IP}:$${MGMT} \\"; \
		echo "    -L $${ADMIN}:$${IP}:$${ADMIN} \\"; \
		echo "    -L $${ANL}:$${IP}:$${ANL} \\"; \
		echo "    -L 8404:$${IP}:8404 \\"; \
		echo "    -L 9091:127.0.0.1:9091 \\"; \
		echo "    -L 3001:127.0.0.1:3001 \\"; \
		echo "    $$SERVER"; \
		echo ""; \
		echo "Then browse to:"; \
		echo "  http://localhost:$${MGMT}        — Management UI  ($(NAME))"; \
		echo "  http://localhost:$${ADMIN}        — Admin API      ($(NAME))"; \
		echo "  http://localhost:$${ANL}          — Analytics      ($(NAME))"; \
		echo "  http://localhost:8404/stats        — HAProxy stats  ($(NAME))"; \
		echo "  http://localhost:9091              — Prometheus     (shared)"; \
		echo "  http://localhost:3001              — Grafana        (shared)"; \
		echo ""; \
		if [ -n "$(HOST)" ]; then \
			echo "Opening tunnel to $(HOST) ...  (Ctrl-C to close)"; \
			echo ""; \
			ssh -N \
				-L $${MGMT}:$${IP}:$${MGMT} \
				-L $${ADMIN}:$${IP}:$${ADMIN} \
				-L $${ANL}:$${IP}:$${ANL} \
				-L 8404:$${IP}:8404 \
				-L 9091:127.0.0.1:9091 \
				-L 3001:127.0.0.1:3001 \
				$(HOST); \
		fi \
	'

## Infrastructure monitoring targets
test-infra-monitoring:
	python3 -m pytest tests/unit/test_infra_alerts.py tests/unit/test_infra_dashboard.py -v

test-infra-monitoring-integration:
	@echo "Requires monitoring stack: cd docker && docker compose -f docker-compose.monitoring.yml up -d"
	@./tests/integration/infra-monitoring/check_cadvisor_metrics.sh
	@./tests/integration/infra-monitoring/check_haproxy_exporter.sh

## Roadmap sync
sync:
	python3 scripts/sync-roadmap.py

## Docker consistency targets
test-docker-consistency:
	python3 -m pytest tests/unit/test_docker_consistency.py \
	                 tests/integration/test_dockerfile_coverage.py -v

# Compose-config validation (docker-compose config --quiet on poc/test/prod).
# This is a lint, not a test — included in `lint-infra` → `lint-all`.
# See also `lint-docker` which performs a superset of this check across all
# compose overlays (poc, python-legacy, test, monitoring, prod, scale).
lint-compose-config:
	REDIS_PASSWORD=lint BACKEND_HOST=lint \
	MANAGEMENT_JWT_SECRET=lint MANAGEMENT_ADMIN_USER=lint MANAGEMENT_ADMIN_PASSWORD=lint \
	  docker compose -f deploy/docker/docker-compose.poc.yml --env-file .env config --quiet
	docker compose -f deploy/docker/docker-compose.test.yml config --quiet
	BACKEND_HOST=lint \
	  docker compose -f deploy/docker/docker-compose.prod.yml config --quiet

# Deprecated alias — kept so runbooks still resolve. Prefer lint-compose-config.
test-compose-config-lint: lint-compose-config
	@echo "  (note: 'test-compose-config-lint' is a lint check — prefer 'make lint-compose-config')"

## GDPR compliance targets
test-gdpr-compliance:
	python3 -m pytest tests/unit/test_gdpr_delete.py -v

## ── Lint target hierarchy ─────────────────────────────────────────────────
# Individual new lint targets — each wraps one tool/domain.
# Aggregates follow at the bottom.

# pylint errors-only: catches real semantic bugs (undefined names, unreachable
# code, attribute errors) that mypy and ruff don't cover.
lint-pylint:
	@echo "=== pylint: Python semantic analysis (errors only) ==="
	@python3 -m pylint --errors-only src/ proxy.py security/ \
		&& echo "✓ pylint passed"

# semgrep with auto-config: cross-language pattern matching for real bugs,
# dangerous API usage, and security anti-patterns.
# Uses locally installed semgrep (already in requirements.txt).
lint-semgrep:
	@echo "=== semgrep: cross-language semantic analysis ==="
	@if command -v semgrep >/dev/null 2>&1; then \
		semgrep scan --config=auto --quiet \
			--exclude=node_modules --exclude=.git --exclude='*.pyc' \
			--exclude='reports/' --exclude='.mypy_cache/' \
			. \
		&& echo "  ✓ semgrep passed (0 findings)"; \
	else \
		echo "  ⚠ semgrep not installed — skipping (install: pip install semgrep)"; \
	fi

# checkov: IaC security scan for misconfigurations in Dockerfiles, Compose
# files, Ansible, and Helm charts (running as root, exposed secrets, etc.).
# --soft-fail surfaces findings without blocking; harden once baseline is clean.
lint-checkov:
	@echo "=== checkov: IaC security misconfiguration scan ==="
	@docker run --rm \
		-v "$(PWD):/app" \
		bridgecrew/checkov \
		--directory /app/docker \
		--directory /app/deploy \
		--skip-path /app/node_modules \
		--quiet --compact --soft-fail \
		&& echo "✓ checkov complete (soft-fail: review findings above)"

# haproxy -c: semantic config validation — catches invalid ACLs, bad backend
# references, port conflicts, and other logical errors beyond syntax.
lint-haproxy:
	@echo "=== haproxy -c: HAProxy config validation ==="
	@docker run --rm \
		--add-host proxy:127.0.0.1 \
		-v "$(PWD)/config:/config:ro" \
		-v "$(PWD)/deploy/haproxy:/ha-config:ro" \
		haproxy:2.8.5-alpine \
		sh -c "haproxy -c -f /config/haproxy.cfg \
			&& echo '  config/haproxy.cfg                                 OK' \
			; haproxy -c -f /ha-config/haproxy.cfg \
			&& echo '  deploy/haproxy/haproxy.cfg                              OK'" \
		&& echo "✓ HAProxy config valid"

# helm lint: Helm chart structural and semantic validation — catches missing
# required values, incorrect apiVersions, bad Go template syntax.
lint-helm:
	@echo "=== helm lint: Helm chart validation ==="
	@docker run --rm \
		-v "$(PWD)/deploy/helm:/charts:ro" \
		alpine/helm:latest \
		lint /charts/ja4proxy \
		&& echo "✓ Helm chart valid"

# actionlint: GitHub Actions workflow validation — catches syntax errors,
# invalid triggers, bad property names, and shell injection risks.
lint-github-actions:
	@echo "=== actionlint: GitHub Actions workflow validation ==="
	@docker run --rm \
		-v "$(PWD):/repo:ro" \
		-w /repo \
		rhysd/actionlint:latest \
		-color \
		-shellcheck= \
		.github/workflows/*.yml \
		&& echo "✓ GitHub Actions valid"

# ansible-lint: Ansible semantic validation — catches shell-when-command-works,
# hardcoded passwords, missing become, handler ordering, deprecated modules.
lint-ansible:
	@echo "=== ansible-lint: Ansible playbook + role validation ==="
	@docker run --rm \
		-v "$(PWD)/deploy/ansible:/ansible:ro" \
		pipelinecomponents/ansible-lint:latest \
		ansible-lint /ansible --exclude /ansible/roles/ja4proxy/molecule \
		&& echo "✓ Ansible lint passed"

# markdownlint: Markdown structural quality — broken heading hierarchy,
# inconsistent list markers, missing blank lines, bare URLs, fence language.
lint-markdown:
	@echo "=== markdownlint: Markdown structure ==="
	@docker run --rm \
		-v "$(PWD):/work:ro" \
		davidanson/markdownlint-cli2:latest \
		"**/*.md" "#node_modules/**" "#.git/**" "#reports/**" \
		&& echo "✓ Markdown lint passed"

# codespell: typo detection in docs and code — catches common misspellings
# that survive spell check because they're valid words in wrong context.
lint-spelling:
	@echo "=== codespell: typo detection ==="
	@docker run --rm \
		-v "$(PWD):/work:ro" -w /work \
		python:3.14-slim \
		sh -c "pip install codespell -q && codespell \
			--skip='*.pyc,*.png,*.pdf,*.bin,*.gz,*.zip,*.mmdb,*.csv,*.html,*.tex,*.log,*.sum,node_modules,.git,reports' \
			--ignore-words-list='ba,fo,nin,ser,hist,dur,nd,ot,te,aNULL,WIT,wit,CrOS,froms,CNA,intoto,tru,strat,SME,CAF,pre-select,Pre-select,pre-selected,re-uses,re-use,pre-empt' \
			." \
		&& echo "✓ Spelling check passed"

# TOML syntax + parse validation. tomllib (built-in since 3.11) validates
# structure and types, not just character encoding.
lint-toml:
	@echo "=== TOML validation ==="
	@python3 scripts/lint_toml.py
	@echo "✓ TOML valid"

# checkmake: Makefile semantic validation — missing .PHONY declarations,
# tabs vs spaces, recursive make anti-patterns, undefined variables.
lint-makefiles:
	@echo "=== checkmake: Makefile validation ==="
	@docker run --rm \
		-v "$(PWD):/repo:ro" \
		cytopia/checkmake:latest \
		--config=/repo/.checkmake.ini \
		/repo/Makefile \
		&& echo "✓ Makefile lint passed"

# go mod verify: confirms that module dependencies on disk match the checksums
# in go.sum — detects tampered or corrupted dependencies.
lint-go-mod:
	@echo "=== go mod verify: module integrity ==="
	@$(GO) mod verify \
		&& echo "✓ Go module integrity verified"

# ── Aggregates ────────────────────────────────────────────────────────────────

# Python: static analysis gates + security SAST + deeper semantic (pylint)
lint-python: lint-static lint-security lint-pylint

# Go: vet + comprehensive golangci-lint + module integrity
lint-go: go-lint lint-go-full lint-go-mod

# Cross-language SAST: semgrep pattern analysis + IaC security misconfigs
lint-sast: lint-semgrep lint-checkov

# Infrastructure: every file-type validator for deployed/config artefacts
lint-infra: lint-docker lint-shell lint-yaml lint-lua lint-json \
            lint-haproxy lint-makefiles lint-toml lint-ansible lint-helm \
            lint-github-actions lint-compose-config scan-dockerfiles

# Observability config: Prometheus alert/recording rules + Alertmanager
lint-observability: lint-prom lint-alertmanager

# Supply chain: secrets committed to history + CVE dep scan + image CVEs (advisory)
lint-supply-chain: lint-secrets lint-deps
	@echo "=== Supply Chain: Advisory image and filesystem scans ==="
	@docker run --rm -v "$(PWD):/repo" aquasec/trivy:0.70.0 fs /repo --severity HIGH,CRITICAL --exit-code 0 || true
	@make scan-images || true
	@make scan-first-party || true

# Documentation: frontmatter + phase consistency + links + structure + spelling
lint-docs-all: lint-docs lint-phases link-check check-paths lint-markdown lint-spelling

# Run every linter — the single entry point for full validation
lint-all: lint-python lint-go lint-sast lint-infra lint-observability \
          lint-supply-chain lint-docs-all
	@echo ""
	@echo "✓ lint-all complete — all linters passed"

## Lint hierarchy targets
test-lint-hierarchy:
	python3 -m pytest tests/lint-hierarchy/ -v

## Provisioning targets — Terraform Provider + Emergency Playbooks
test-provisioning:
	cd deploy/terraform-provider && GOROOT=/snap/go/current go test ./internal/... -v -count=1
	python3 -m pytest tests/integration/test_emergency_playbooks.py -v

# PHONY declarations (appended per CLAUDE.md — do not modify line 3)
.PHONY: lint-pylint lint-semgrep lint-checkov lint-haproxy lint-helm lint-ansible \
        lint-markdown lint-spelling lint-toml lint-makefiles lint-go-mod \
        lint-python lint-go lint-sast lint-infra lint-observability \
        lint-github-actions \
        lint-supply-chain \
        lint-docs-all lint-all check-paths sync \
        lint-compose-config test-compose-config-lint test-component-suites \
        test-mgmt-api test-mgmt-api-unit test-mgmt-api-events \
        test-infra-monitoring test-infra-monitoring-integration \
        test-docker-consistency test-gdpr-compliance \
        test-lint-hierarchy test-provisioning

# ── Component-level aggregates ──────────────────────────────────────────────
## Component test targets
# Roll-up of every per-component test-* target. Some targets straddle Go+Python,
# so this is kept separate from `make test` (which is the pytest-driven local
# runner). Run this when validating a release or touching core code.
test-component-suites: test-mgmt-api test-slo test-logging-webhook test-policy-validator \
             test-cli test-compliance test-infra-monitoring test-docker-consistency \
             test-gdpr-compliance test-lint-hierarchy test-provisioning
	@echo ""
	@echo "✓ test-component-suites complete — all component test suites passed"

## Logging and webhook targets
test-logging-webhook:
	GOROOT=/snap/go/current go test ./internal/logging/... ./internal/webhook/... -v
	python3 -m pytest tests/unit/test_ecs_logging.py -v

validate-ecs-schema:
	python3 -c "import json,jsonschema; from jsonschema import Draft7Validator,FormatChecker; schema=json.load(open('config/integrations/ecs-schema.json')); sample=json.load(open('config/integrations/ecs-sample-event.json')); errors=list(Draft7Validator(schema,format_checker=FormatChecker()).iter_errors(sample)); [(__import__('sys').exit(1) or print('ERROR:',e.message)) for e in errors] if errors else print('ECS schema validation: OK')"

.PHONY: test-logging-webhook validate-ecs-schema

## Policy targets
test-policy-validator:
	python3 -m pytest tests/unit/test_policy_validator.py tests/integration/test_policy_apply.py -v

.PHONY: test-policy-validator

## OpenAPI targets
openapi-spec:
	MANAGEMENT_TEST_MODE=1 python3 management/scripts/export_openapi.py

.PHONY: openapi-spec

## CLI targets
test-cli:
	mkdir -p bin
	GOROOT=/snap/go/current go build -o bin/ja4proxy-cli ./cmd/ja4proxy-cli/
	GOROOT=/snap/go/current go vet ./internal/cli/...
	GOROOT=/snap/go/current go test ./internal/cli/... -v -count=1
	GOROOT=/snap/go/current python3 -m pytest tests/integration/test_cli_parity.py -v
.PHONY: test-cli

## Compliance targets
test-compliance:
	GOROOT=/snap/go/current go vet ./internal/compliance/...
	GOROOT=/snap/go/current go test ./internal/compliance/... -v -count=1
	GOROOT=/snap/go/current go test ./internal/cli/commands/ -run "TestRunDSAR|TestRunPCIDSSPack|TestRunReportGenerate|TestRunPurgeExpired|TestRunSignalCategories|TestRunConnectionsExport" -v -count=1
	python3 -m pytest management/tests/test_compliance_classifier.py management/tests/test_compliance_purge.py management/tests/test_compliance_pack.py management/tests/test_compliance_renderer.py management/tests/test_compliance_routes.py management/tests/test_connections_pagination.py -v

test-compliance-go:
	GOROOT=/snap/go/current go test ./internal/compliance/... -v -count=1

test-compliance-python:
	python3 -m pytest management/tests/test_compliance_classifier.py management/tests/test_compliance_purge.py management/tests/test_compliance_pack.py management/tests/test_compliance_renderer.py management/tests/test_compliance_routes.py management/tests/test_connections_pagination.py -v

test-compliance-parity:
	GOROOT=/snap/go/current go test ./internal/compliance/ -run TestCrossLanguageParity -v
	python3 -m pytest management/tests/test_compliance_classifier.py -k "parity" -v

.PHONY: test-compliance test-compliance-go test-compliance-python test-compliance-parity

# ── Go fuzz / property / chaos / bench targets ─────────────────────
# These targets are independent of the existing test-go-* targets which run
# Python-driven Go integration tests against a live binary.

test-go-fuzz-smoke:
	GOROOT=/snap/go/current go test -run=^$$ -fuzz=FuzzClientHello$$ -fuzztime=10s ./cmd/proxy/
	GOROOT=/snap/go/current go test -run=^$$ -fuzz=FuzzReadProxyProtocol$$ -fuzztime=10s ./cmd/proxy/
	GOROOT=/snap/go/current go test -run=^$$ -fuzz=FuzzReadProxyProtocolV2$$ -fuzztime=10s ./cmd/proxy/

test-go-property:
	GOROOT=/snap/go/current go test -v -run TestProperty ./internal/security/

test-go-chaos-unit:
	GOROOT=/snap/go/current go test -v -run 'TestPipeline_(RedisOutage|PartialOutage|DialFlip)' ./internal/security/

bench-go-pipeline:
	GOROOT=/snap/go/current go test -bench=BenchmarkPipeline -benchmem -run=^$$ ./cmd/proxy/

validation-report:
	python3 scripts/generate_validation_report.py

.PHONY: test-go-fuzz-smoke test-go-property test-go-chaos-unit bench-go-pipeline validation-report

## Phase 63 targets — SLO validation and reporting
validate-slo-rules:
	@command -v promtool >/dev/null 2>&1 && { \
		promtool check rules deploy/monitoring/prometheus/slo_recording_rules.yml; \
		promtool check rules deploy/monitoring/alertmanager/rules/slo_alerts.yml; \
		echo "SLO recording rules and alert rules are syntactically valid."; \
	} || { \
		python3 -c "import yaml; yaml.safe_load(open('deploy/monitoring/prometheus/slo_recording_rules.yml')); yaml.safe_load(open('deploy/monitoring/alertmanager/rules/slo_alerts.yml')); print('YAML structurally valid (promtool not installed)')"; \
	}

slo-report:
	@echo "=== JA4proxy SLO Report ==="
	@curl -sg 'http://localhost:9090/api/v1/query?query=job:ja4proxy_availability:ratio_rate5m' \
		| python3 -c "import sys,json; d=json.load(sys.stdin); v=d['data']['result']; print('Availability (5m):', round(float(v[0]['value'][1])*100, 4) if v else 'NO DATA', '%')"
	@curl -sg 'http://localhost:9090/api/v1/query?query=job:ja4proxy_latency_p99_good:ratio_rate5m' \
		| python3 -c "import sys,json; d=json.load(sys.stdin); v=d['data']['result']; print('Latency    (5m):', round(float(v[0]['value'][1])*100, 4) if v else 'NO DATA', '%')"
	@curl -sg 'http://localhost:9090/api/v1/query?query=job:ja4proxy_redis_correctness:ratio_rate5m' \
		| python3 -c "import sys,json; d=json.load(sys.stdin); v=d['data']['result']; print('Redis      (5m):', round(float(v[0]['value'][1])*100, 4) if v else 'NO DATA', '%')"

test-slo:
	GOROOT=/snap/go/current go test ./internal/metrics/... ./internal/redis/... -count=1
	python3 -c "import yaml; yaml.safe_load(open('deploy/monitoring/prometheus/slo_recording_rules.yml')); yaml.safe_load(open('deploy/monitoring/alertmanager/rules/slo_alerts.yml')); print('YAML OK')"

.PHONY: validate-slo-rules slo-report test-slo

## CI local targets
ci-local: ## Run the same fast checks the CI workflow runs (Go + Python tests)
	GOROOT=/snap/go/current go test ./...
	python3 -m pytest tests/ --ignore=tests/integration/test_docker_stack.py -x -q --timeout=60

.PHONY: ci-local

## Phase 64a targets
smoke-docker: ## Run Docker Compose smoke test
	bash scripts/smoke/test_docker_compose.sh

.PHONY: smoke-docker

## Phase 64b targets
smoke-k8s: ## Run Helm + kind smoke test
	bash scripts/smoke/test_helm_kind.sh

.PHONY: smoke-k8s

## Phase 64h targets
measure-mttr: ## Measure MTTR for DR scenarios
	bash scripts/measure_mttr.sh

.PHONY: measure-mttr

## Phase 86b targets — Load testing harness
load-test: ## Run JA4proxy load test
	python3 scripts/load_test.py \
		--target $(LOAD_TEST_TARGET) \
		--duration $(LOAD_TEST_DURATION) \
		--rps $(LOAD_TEST_RPS) \
		--scenario $(LOAD_TEST_SCENARIO)

load-test-baseline: ## Run baseline load test (localhost:8080, 60s, 1000 rps)
	LOAD_TEST_TARGET=localhost:8080 \
	LOAD_TEST_DURATION=60 \
	LOAD_TEST_RPS=1000 \
	LOAD_TEST_SCENARIO=baseline \
	$(MAKE) load-test

load-test-report: ## Show latest load test reports
	@echo "Latest benchmark reports:"
	@ls -lt test-results/load-test/ 2>/dev/null | head -5 || echo "No reports found"

.PHONY: load-test load-test-baseline load-test-report

## Phase 86h targets
lint-alert-urls: ## Verify Alertmanager runbook_url values are up to date
	@echo "Checking alertmanager runbook URLs..."
	@python3 scripts/fix_runbook_urls.py \
		--rules-dir deploy/monitoring/alertmanager/rules/ \
		--mapping docs/phases/PHASE_86h_runbook_mapping.yml \
		--check

.PHONY: lint-alert-urls

# Quick-start and performance test targets
quick-start: ## Start the proxy with default config (builds if needed)
	bash scripts/quick-start.sh

perf-test-basic: ## Run basic performance test against a local proxy
	bash scripts/basic_perf_test.sh

.PHONY: quick-start perf-test-basic

# Single quality gate — linters + coverage thresholds
quality: lint-all lint-coverage ## Run all linters + coverage checks in one shot
	@echo ""
	@echo "=== Go coverage check ==="
	@GOROOT=/snap/go/current go test ./... -coverprofile=/tmp/go_cover_quality.out -count=1 > /dev/null 2>&1 \
		&& GOROOT=/snap/go/current go tool cover -func=/tmp/go_cover_quality.out \
			| tail -1 | awk '{gsub(/%/,"",$$NF); if($$NF+0 < 50) {print "FAIL: Go coverage "$$NF"% < 50%"; exit 1} else print "  ✓ Go coverage "$$NF"%"}'
	@echo ""
	@echo "✓ quality complete — all checks passed"

.PHONY: quality

# Canonical findings register
verify-findings: ## Validate docs/security/findings.yaml schema and referential integrity
	@python3 scripts/findings_register.py validate

verify-findings-green: ## Run only the regression tests backing findings.yaml entries (fast signal)
	@python3 scripts/findings_register.py verify-regression-tests --stub-green

findings-render: ## Regenerate docs/security/FINDINGS_REGISTER.md from findings.yaml
	@python3 scripts/findings_register.py render

findings-list: ## List open findings (add FINDINGS_ARGS=... to pass flags, e.g. --severity HIGH)
	@python3 scripts/findings_register.py list $(FINDINGS_ARGS)

verify-manifest-closeout: ## Manifest close-out gate — validate register, required docs, ADRs, manifest
	@python3 scripts/phase_121_verify.py

.PHONY: verify-findings verify-findings-green findings-render findings-list phase-121-verify verify-manifest-closeout test-compliance-language test-evidence-paths test-compliance test-attack-mapping test-doc-links

# phase-107h: regulatory-conformance regression guards
test-compliance-language: ## Phase 107h.1 — fail if "certified"/"compliant" appears in self-assessed compliance docs
	@python3 -m pytest tests/test_compliance_language.py -v

test-evidence-paths: ## Phase 107h.2 — fail if conformance docs cite repo paths that don't exist
	@python3 -m pytest tests/test_compliance_evidence_paths.py -v

test-compliance: test-compliance-language test-evidence-paths ## Phase 107h — all regulatory-conformance regression guards

# phase-107f: ATT&CK mapping CI gate
test-attack-mapping: ## Phase 107f.4 — fail if ATT&CK mapping rows lack confidence labels or cite missing source files
	python3 -m pytest tests/test_attack_mapping.py -v

# phase-107w.3: doc-link check (requires lychee installed locally — same tool the CI workflow runs)
test-doc-links: ## Phase 107w.3 — lychee-check conformance + audience-scoped docs for broken internal links
	@command -v lychee >/dev/null 2>&1 || { \
		echo "lychee not installed. Install: https://github.com/lycheeverse/lychee#installation"; \
		echo "Or run via Docker: docker run --rm -v \$$PWD:/input lycheeverse/lychee --no-progress --accept 200,204,301,302,403,429 /input/docs/compliance /input/docs/for-architects /input/docs/for-compliance /input/docs/for-website-owners /input/docs/security/CVD_POLICY.md /input/docs/decisions/ADR-107a-slsa-level-3.md /input/SECURITY.md"; \
		exit 1; \
	}
	lychee --no-progress --accept 200,204,301,302,403,429 \
		'docs/compliance/**/*.md' \
		'docs/for-architects/**/*.md' \
		'docs/for-compliance/**/*.md' \
		'docs/for-website-owners/**/*.md' \
		'docs/security/CVD_POLICY.md' \
		'docs/decisions/ADR-107*.md' \
		'SECURITY.md'
