# Makefile for JA4 Proxy

.PHONY: help build rebuild test test-unit test-chaos test-adversarial test-calibrate test-docker lint lint-docker lint-shell lint-yaml lint-prom lint-deps lint-secrets scan-images clean deploy-poc deploy-enterprise smoke-test flush-redis attack-status top-attackers block-ja4 block-ip unblock-ip fetch-db list-pending approve-all geoip-report geoip-monitor geoip-watch update-geoip check-geoip start start-monitoring stop stop-clean status dial ssh-tunnels go-build go-test go-lint go-start go-stop go-switch go-rollback go-parity capture-fixtures go-build-ja4check test-go-docker test-go-integration test-go-chaos test-go-perf test-go capture-fixtures-browser

# Load machine-specific worker count (generated by: make test-calibrate)
-include .local/machine.mk
WORKERS ?= auto

# Default target
help:
	@echo ""
	@echo "JA4proxy — Available make targets"
	@echo ""
	@echo "── Startup / Shutdown ──────────────────────────────────────"
	@echo "  start             - Start full stack (POC + Prometheus/Grafana)"
	@echo "  start-monitoring  - Start monitoring stack only"
	@echo "  stop              - Stop all services (keep Redis data)"
	@echo "  stop-clean        - Stop all services AND wipe volumes (fresh slate)"
	@echo "  status            - Show health of all services + security state"
	@echo "  logs              - Stream proxy container logs"
	@echo ""
	@echo "── Configuration ───────────────────────────────────────────"
	@echo "  Edit .env to set:"
	@echo "    BACKEND_HOST    - IP/hostname of your real backend server"
	@echo "    BACKEND_PORT    - Backend port (default 443)"
	@echo "    REDIS_PASSWORD  - Auto-generated on first start"
	@echo "    GRAFANA_PASSWORD- Auto-generated on first start"
	@echo "    JA4DB_API_KEY   - Optional ja4db.com API key"
	@echo "  dial LEVEL=<0-100> - Set the blocking dial via pubsub"
	@echo ""
	@echo "── Operations ──────────────────────────────────────────────"
	@echo "  ssh-tunnels       - Print SSH tunnel command for remote UI access"
	@echo ""
	@echo "── Incident Response (no restart needed) ───────────────────"
	@echo "  attack-status     - Quick security snapshot (active bans, block rate)"
	@echo "  top-attackers     - Top 10 fingerprints by traffic right now"
	@echo "  block-ja4 FP=...  - Blacklist a JA4 fingerprint (instant TCP RST)"
	@echo "  block-ip  IP=...  - Hard-block an IP for 1 hour"
	@echo "  unblock-ip IP=... - Remove all blocks for an IP"
	@echo "  flush-redis       - Reset bans/blocks/rates (keeps blacklist/whitelist)"
	@echo ""
	@echo "── Threat Intelligence ─────────────────────────────────────"
	@echo "  fetch-db          - Fetch new malicious fingerprints from ja4db / FoxIO"
	@echo "  list-pending      - Show fingerprints awaiting admin approval"
	@echo "  approve-all       - Approve all pending fingerprints"
	@echo "  update-geoip      - Download latest IP2Location LITE database (monthly)"
	@echo "  check-geoip       - Check age of current GeoIP database"
	@echo "  geoip-report      - Full blocking report (countries, CIDRs, fingerprints)"
	@echo "  geoip-monitor     - Auto-block attacking countries (run once)"
	@echo "  geoip-watch       - Auto-block attacking countries (continuous loop)"
	@echo ""
	@echo "── Development / Testing (Python) ──────────────────────────"
	@echo "  rebuild           - Full clean rebuild from scratch (wipe volumes + images, rebuild, start)"
	@echo "  build             - Build Docker images (incremental)"
	@echo "  test              - Run all tests locally in parallel (fast, no Docker)"
	@echo "  test-unit         - Run unit tests only"
	@echo "  test-chaos        - Run chaos/resilience tests only"
	@echo "  test-adversarial  - Run adversarial/fuzz tests only"
	@echo "  test-calibrate    - Benchmark this machine and store worker count"
	@echo "  test-docker       - Run tests inside Docker (CI / clean environment)"
	@echo "  smoke-test        - Quick sanity check"
	@echo "  lint              - black + flake8 + mypy"
	@echo "  lint-docker       - hadolint (Dockerfiles) + docker compose config (all compose files)"
	@echo "  lint-shell        - shellcheck all .sh scripts (error level)"
	@echo "  lint-yaml         - yamllint config/ and monitoring/ YAML files"
	@echo "  lint-prom         - promtool semantic validation of alert + recording rules"
	@echo "  lint-deps         - pip-audit (Python) + govulncheck (Go) CVE dependency scan"
	@echo "  lint-secrets      - gitleaks scan of git history for accidentally committed secrets"
	@echo "  scan-images       - Trivy CVE scan of third-party images (fails on CRITICAL)"
	@echo "  clean             - Stop + remove all containers and volumes"
	@echo ""
	@echo "── Go Proxy ─────────────────────────────────────────────────"
	@echo "  go-build          - Build Go proxy binary to bin/ja4proxy"
	@echo "  go-test           - Run all Go unit tests"
	@echo "  go-lint           - Run go vet on Go code"
	@echo "  go-start          - Start Go proxy alongside Python proxy (parallel validation)"
	@echo "  go-stop           - Stop Go proxy container"
	@echo "  go-switch         - Switch HAProxy to route traffic to Go proxy"
	@echo "  go-rollback       - Switch HAProxy back to Python proxy"
	@echo "  go-parity         - Run cross-language parity tests (both proxies must be running)"
	@echo ""

# ── Startup / Shutdown ────────────────────────────────────────────────────────

# Start full stack (POC + monitoring)
start:
	@./scripts/start-all.sh

# Start monitoring stack only (Prometheus / Grafana / Loki)
start-monitoring:
	@./scripts/start-monitoring.sh

# Stop all services (keep Redis data)
stop:
	@./scripts/stop-all.sh

# Stop all services AND remove all volumes (fresh slate)
stop-clean:
	@./scripts/stop-all.sh --clean

# Show health of all services + security state
status:
	@./scripts/status.sh

# ── Build ──────────────────────────────────────────────────────────────────────

# Build Docker images
build:
	@echo "Building Docker images..."
	docker compose -f docker-compose.poc.yml build

# Run all tests locally in parallel (fast — no Docker required)
test:
	@./scripts/run-local-tests.sh $(ARGS)

# Run unit tests only
test-unit:
	@python3 -m pytest tests/unit/ -n $(WORKERS) --dist=loadfile --timeout=60 --tb=short $(ARGS)

# Run chaos/resilience tests only
test-chaos:
	@python3 -m pytest tests/chaos/ -n $(WORKERS) --dist=loadfile --timeout=60 --tb=short $(ARGS)

# Run adversarial/fuzz tests only (no parallelism — some are stateful)
test-adversarial:
	@python3 -m pytest tests/adversarial/ --timeout=60 --tb=short $(ARGS)

# Benchmark this machine and store worker count in .local/machine.mk
test-calibrate:
	@python3 scripts/detect_workers.py

# Run tests inside Docker (CI / clean environment)
test-docker:
	@./scripts/run-tests.sh

# Run quick smoke test
smoke-test:
	@./scripts/smoke-test.sh

# Run linting
lint:
	docker run --rm -v $(PWD):/app python:3.11-slim sh -c "cd /app && pip install black flake8 mypy bandit pytest-cov && black --check proxy.py security/ src/ && flake8 proxy.py security/ src/ 2>/dev/null && mypy proxy.py security/ src/ 2>/dev/null && bandit -r proxy.py security/ src/ && echo \"✓ Linting passed\""

# Security scanning with bandit (report all issues)
lint-security:
	docker run --rm -v $(PWD):/app python:3.11-slim sh -c "cd /app && pip install bandit && bandit -r proxy.py security/ src/ 2>/dev/null"

# Type checking with mypy (supress output)
lint-types:
	docker run --rm -v $(PWD):/app python:3.11-slim sh -c "cd /app && pip install mypy && mypy proxy.py security/ src/ 2>/dev/null || echo 'Mypy warnings above, see baseline docs/reports/MYPY_BASELINE.md'"

# Code quality with flake8 (suppress output)
lint-quality:
	docker run --rm -v $(PWD):/app python:3.11-slim sh -c "cd /app && pip install flake8 && flake8 proxy.py security/ src/ 2>/dev/null || echo 'Flake8 warnings above, see baseline docs/QUICK_REFERENCE.md'"

# Coverage reporting with pytest-cov
lint-coverage:
	python3 -m pytest tests/ --cov=src --cov-report=term-missing --cov-report=html:reports/coverage/html --cov-fail-under=80 || (echo "Failed to reach 80% coverage threshold"; exit 1)

# Lint Dockerfiles (hadolint) and validate docker-compose files (docker compose config).
# Ignored rules are consciously accepted — see .hadolint.yaml for rationale.
# docker/docker-compose.test.yml is an overlay stub; it cannot be validated standalone.
HADOLINT_IGNORE := --ignore DL3008 --ignore DL3013 --ignore DL3015 --ignore DL3018 --ignore DL3059
HADOLINT_DOCKERFILES := docker/Dockerfile docker/Dockerfile.mockbackend docker/Dockerfile.test \
	docker/Dockerfile.trafficgen Dockerfile-go src/analytics/Dockerfile tarpit/Dockerfile \
	tests/docker/Dockerfile.python-proxy tests/docker/Dockerfile.recorder \
	tests/docker/Dockerfile.test-runner tests/docker/Dockerfile.tls-backend

lint-docker:
	@echo "=== hadolint: Dockerfiles ==="
	@for f in $(HADOLINT_DOCKERFILES); do \
		printf "  %-50s" "$$f"; \
		result=$$(docker run --rm -i hadolint/hadolint hadolint $(HADOLINT_IGNORE) --no-color - < "$$f" 2>&1); \
		if [ -n "$$result" ]; then echo "FAIL"; echo "$$result"; exit 1; fi; \
		echo "OK"; \
	done
	@echo ""
	@echo "=== docker compose config: compose files ==="
	@BACKEND_HOST=lint-placeholder docker compose -f docker-compose.poc.yml config --quiet \
		&& echo "  docker-compose.poc.yml                             OK"
	@BACKEND_HOST=lint-placeholder docker compose -f docker-compose.poc.yml -f docker-compose.go.yml config --quiet \
		&& echo "  docker-compose.go.yml (overlay)                    OK"
	@docker compose -f docker-compose.test.yml config --quiet \
		&& echo "  docker-compose.test.yml                            OK"
	@docker compose -f docker/docker-compose.monitoring.yml config --quiet \
		&& echo "  docker/docker-compose.monitoring.yml               OK"
	@BACKEND_HOST=lint-placeholder docker compose -f docker/docker-compose.prod.yml config --quiet \
		&& echo "  docker/docker-compose.prod.yml                     OK"
	@echo ""
	@echo "✓ Docker lint passed"

# Lint shell scripts with shellcheck (error-level only; warnings are advisory).
# SC2154 suppressed: variables sourced from .env are referenced but not assigned in-script.
SHELL_SCRIPTS := $(shell find . -name "*.sh" -not -path "./.git/*" -not -path "./node_modules/*" | sort)
lint-shell:
	@echo "=== shellcheck: shell scripts ==="
	@fail=0; \
	for f in $(SHELL_SCRIPTS); do \
		printf "  %-60s" "$$f"; \
		result=$$(docker run --rm -i koalaman/shellcheck:stable \
			--severity=error --exclude=SC2154 - < "$$f" 2>&1); \
		if [ -n "$$result" ]; then echo "FAIL"; echo "$$result"; fail=1; \
		else echo "OK"; fi; \
	done; \
	[ $$fail -eq 0 ] || exit 1
	@echo ""
	@echo "✓ Shell lint passed"

# Scan third-party Docker images for HIGH/CRITICAL CVEs (Trivy).
# This is informational — images we don't control may lag on patch releases.
# Fails only on CRITICAL findings; HIGH findings are reported but non-blocking.
# Scans only pinned third-party images (not images we build ourselves).
TRIVY_IMAGES := haproxy:2.8-alpine \
	redis/redis-stack:latest \
	oliver006/redis_exporter:v1.55.0 \
	prom/prometheus:v2.48.0 \
	prom/alertmanager:v0.26.0 \
	grafana/grafana:10.2.0 \
	grafana/loki:2.9.0 \
	grafana/promtail:2.9.0

scan-images:
	@echo "=== Trivy: third-party image CVE scan (HIGH + CRITICAL) ==="
	@echo "    Fails on CRITICAL; HIGH findings are reported but advisory."
	@echo ""
	@fail=0; \
	for img in $(TRIVY_IMAGES); do \
		echo "  Scanning $$img ..."; \
		result=$$(docker run --rm aquasec/trivy:latest image \
			--severity HIGH,CRITICAL --exit-code 0 \
			--no-progress --scanners vuln \
			--format table "$$img" 2>&1 | grep -E "CRITICAL|HIGH|Total:" || true); \
		critical=$$(echo "$$result" | grep -c "CRITICAL" || true); \
		echo "    $$result"; \
		[ "$$critical" -eq 0 ] || { echo "    ^^^ CRITICAL findings in $$img — update image version"; fail=1; }; \
		echo ""; \
	done; \
	[ $$fail -eq 0 ] || { echo "✗ CRITICAL CVEs found — update image versions in compose files"; exit 1; }
	@echo "✓ Image scan complete"

# Lint YAML config and monitoring files with yamllint.
# Line-length disabled (long Prometheus expressions are unavoidable).
# See .yamllint.yaml for full config.
YAML_DIRS := config monitoring
lint-yaml:
	@echo "=== yamllint: config and monitoring YAML ==="
	@yamllint -c .yamllint.yaml $(YAML_DIRS) && echo "✓ YAML lint passed"

# Validate Prometheus alert and recording rule files with promtool.
# Uses the prometheus container so promtool version matches the deployed version.
PROM_RULES := /monitoring/prometheus/alerts.yml \
	/monitoring/prometheus/recording_rules.yml \
	/monitoring/alertmanager/rules/proxy.rules.yml \
	/monitoring/alertmanager/rules/redis.rules.yml \
	/monitoring/alertmanager/rules/security.rules.yml
lint-prom:
	@echo "=== promtool check rules: Prometheus alert + recording rules ==="
	@docker run --rm --entrypoint promtool \
		-v "$(PWD)/monitoring:/monitoring" \
		prom/prometheus:v2.48.0 \
		check rules $(PROM_RULES) \
		&& echo "✓ Prometheus rules valid"

# Check Python and Go dependencies for known CVEs.
# pip-audit scans requirements.txt; govulncheck scans go.mod.
lint-deps:
	@echo "=== pip-audit: Python dependency CVEs ==="
	@pip-audit -r requirements.txt --no-deps || true
	@pip-audit -r requirements-test.txt --no-deps || true
	@pip-audit -r requirements-analytics.txt --no-deps || true
	@echo "  (CVEs above are advisory — pinned versions may lag; update requirements.txt to remediate)"
	@echo ""
	@echo "=== govulncheck: Go module CVEs ==="
	@GOROOT=/snap/go/current govulncheck ./... && echo "  go.mod: OK"
	@echo ""
	@echo "✓ Dependency scan complete"

# Scan git history for accidentally committed secrets (gitleaks).
# Scans committed files only — working-tree secrets are handled by .gitignore.
# False positives are suppressed in .gitleaks.toml with rationale.
lint-secrets:
	@echo "=== gitleaks: scan git history for secrets ==="
	@docker run --rm \
		-v "$(PWD):/repo" \
		zricethezav/gitleaks:latest detect \
		--source /repo --no-banner --config /repo/.gitleaks.toml \
		&& echo "✓ No secrets found in git history"

# Clean up
clean:
	@echo "Cleaning up containers and volumes..."
	docker compose -f docker-compose.poc.yml down -v --remove-orphans
	docker compose -f docker/docker-compose.prod.yml down -v --remove-orphans
	rm -rf reports/ __pycache__/ .pytest_cache/ .mypy_cache/

# Full clean rebuild from scratch — wipes volumes, removes built images, rebuilds, starts
rebuild:
	@echo "Stopping all services and wiping volumes..."
	docker compose -f docker-compose.poc.yml down -v --remove-orphans --rmi local
	docker compose -f docker/docker-compose.monitoring.yml down -v --remove-orphans --rmi local 2>/dev/null || true
	@echo "Rebuilding all images (no cache)..."
	docker compose -f docker-compose.poc.yml build --no-cache
	@echo "Starting full stack..."
	@./scripts/start-all.sh

# Deploy PoC environment
deploy-poc:
	@./scripts/start-poc.sh

# Deploy enterprise environment
deploy-enterprise:
	@echo "Running enterprise deployment script..."
	@sudo ./scripts/deploy.sh production

# Health checks
health-check:
	@echo "Running health checks..."
	@curl -sf http://localhost:9090/metrics > /dev/null && echo "✓ Proxy metrics OK" || echo "✗ Proxy metrics failed"
	@curl -sk https://localhost:8443/api/health > /dev/null && echo "✓ Backend OK" || echo "✗ Backend failed"
	@docker exec ja4proxy-redis redis-cli -a $${REDIS_PASSWORD:-changeme} ping > /dev/null 2>&1 && echo "✓ Redis OK" || echo "✗ Redis failed"

# View logs
logs:
	docker compose -f docker-compose.poc.yml logs -f proxy

# Flush all transient security state from Redis (bans, blocks, rate windows, audit logs)
# Preserves ja4:whitelist and ja4:blacklist so config survives the flush.
flush-redis:
	@echo "Flushing Redis security state..."
	@REDIS_PASS=$$(grep '^REDIS_PASSWORD=' .env 2>/dev/null | cut -d= -f2); \
	if [ -z "$$REDIS_PASS" ]; then echo "✗ No REDIS_PASSWORD in .env"; exit 1; fi; \
	COUNT=$$(docker exec ja4proxy-redis redis-cli -a "$$REDIS_PASS" --no-auth-warning \
		EVAL "local n=0; \
		      for _,p in ipairs({'rate:*','banned:*','blocked:*','suspicious:*','enforcement:*','audit:*','repeat_block:*'}) do \
		        for _,k in ipairs(redis.call('keys',p)) do redis.call('del',k); n=n+1 end \
		      end; return n" 0 2>/dev/null); \
	echo "✓ Cleared $$COUNT keys (whitelist/blacklist preserved)"

# ── ja4db feed management ─────────────────────────────────────────────────────

# Fetch new malicious fingerprints from FoxIO GitHub / ja4db.com, queue for review
fetch-db:
	@./scripts/fetch-ja4db.sh

# Show fingerprints awaiting approval
list-pending:
	@./scripts/ja4-admin.sh list-pending

# Approve all pending fingerprints (prompts for confirmation)
approve-all:
	@./scripts/ja4-admin.sh approve-all

# ── GeoIP monitoring ───────────────────────────────────────────────────────────

# Full blocking report (countries, CIDRs, fingerprints, Prometheus summary)
geoip-report:
	@./scripts/ja4-admin.sh report

# Run the GeoIP monitor once — auto-blocks attacking countries, respects safe list
geoip-monitor:
	@./scripts/geoip-monitor.sh

# Run geoip-monitor in watch mode (loops every 60s, Ctrl-C to stop)
geoip-watch:
	@./scripts/geoip-monitor.sh --watch

# Download the latest IP2Location LITE country database (run monthly)
# Requires proxy restart after update: make stop && make start
update-geoip:
	@./scripts/update-geoip.sh

# Check how old the current GeoIP database is (no download)
check-geoip:
	@./scripts/update-geoip.sh --check

# ── Incident response shortcuts (wrappers for scripts/ja4-admin.sh) ──────────

# Quick security snapshot: active bans, block totals, top threats
attack-status:
	@./scripts/ja4-admin.sh status

# Top 10 fingerprints by traffic (red = blocked, green = allowed)
top-attackers:
	@./scripts/ja4-admin.sh top 10

# Blacklist a JA4 fingerprint (instant TCP RST, permanent)
# Usage: make block-ja4 FP=t13d190900_9dc949149365_97f8aa674fd9
block-ja4:
	@[ -n "$(FP)" ] || (echo "Usage: make block-ja4 FP=<fingerprint>"; exit 1)
	@./scripts/ja4-admin.sh block-ja4 $(FP)

# Hard-block an IP for 1 hour
# Usage: make block-ip IP=203.0.113.42
block-ip:
	@[ -n "$(IP)" ] || (echo "Usage: make block-ip IP=<address>"; exit 1)
	@./scripts/ja4-admin.sh block-ip $(IP) 3600

# Remove all blocks/bans for an IP
# Usage: make unblock-ip IP=203.0.113.42
unblock-ip:
	@[ -n "$(IP)" ] || (echo "Usage: make unblock-ip IP=<address>"; exit 1)
	@./scripts/ja4-admin.sh unblock-ip $(IP)

# Run performance tests
perf-test:
	@echo "Starting performance tests..."
	@echo "Note: This requires services to be running (make deploy-poc)"
	docker compose -f docker-compose.poc.yml run --rm test locust -f /app/performance/locust_tests.py --host http://proxy:8080 --users 100 --spawn-rate 10 --run-time 5m --headless

# ── Configuration ─────────────────────────────────────────────────────────────

# Set the blocking dial (0 = monitor only, 100 = full blocking)
# Usage: make dial LEVEL=50
dial:
	@[ -n "$(LEVEL)" ] || (echo "Usage: make dial LEVEL=<0-100>"; exit 1)
	@python3 scripts/set_dial.py $(LEVEL)

# ── Operations ────────────────────────────────────────────────────────────────

# Print SSH tunnel command for accessing localhost-only UIs from a remote machine
ssh-tunnels:
	@echo ""
	@echo "To access localhost-only UIs from a remote machine, run this on your laptop:"
	@echo ""
	@echo "  ssh -L 9091:localhost:9091 -L 9093:localhost:9093 -L 8404:localhost:8404 USER@HOST"
	@echo ""
	@echo "Then browse to:"
	@echo "  http://localhost:9091  — Prometheus"
	@echo "  http://localhost:9093  — Alertmanager"
	@echo "  http://localhost:8404/stats  — HAProxy stats"
	@echo "  http://localhost:3001  — Grafana (no tunnel needed, already public)"
	@echo ""

# ── Go Proxy ──────────────────────────────────────────────────────────────────

GOROOT ?= /snap/go/current
GO     := GOROOT=$(GOROOT) go

# Build the Go proxy binary into bin/ja4proxy
go-build:
	@echo "Building Go proxy..."
	@mkdir -p bin
	$(GO) build -o bin/ja4proxy ./cmd/proxy
	@echo "✓ bin/ja4proxy"

# Run all Go unit tests
go-test:
	$(GO) test ./... -count=1

# Run go vet (static analysis)
go-lint:
	$(GO) vet ./...

# Start Go proxy in parallel with Python proxy (parallel validation mode)
# Both proxies share the same Redis instance.
# Go proxy: host port 8082 / metrics 9092
# Python proxy: host port 8080 / metrics 9090 (unchanged)
go-start:
	@echo "Starting Go proxy in parallel (port 8082)..."
	docker compose -f docker-compose.poc.yml -f docker-compose.go.yml up -d go-proxy
	@echo ""
	@echo "  Go proxy:        http://localhost:8082"
	@echo "  Go metrics/health: http://localhost:9092/health"
	@echo "  Python proxy:    http://localhost:8080 (unchanged)"
	@echo ""
	@echo "Run 'make go-parity' after 60s to validate decision parity."

# Stop Go proxy container only (Python proxy unaffected)
go-stop:
	docker compose -f docker-compose.poc.yml -f docker-compose.go.yml stop go-proxy

# Switch HAProxy upstream from Python to Go proxy.
# See docs/runbooks/go_proxy_migration.md for the full cutover checklist.
# Prerequisites: Go proxy must be running and healthy (make go-start).
go-switch:
	@echo "Switching HAProxy to Go proxy..."
	@echo ""
	@echo "Update your HAProxy config to:"
	@echo "  backend ja4proxy"
	@echo "      server go-proxy ja4proxy-go:8080 check"
	@echo "      # server python-proxy ja4proxy:8080 check backup"
	@echo ""
	@echo "Then reload HAProxy:"
	@echo "  docker exec haproxy haproxy -sf \$$(cat /var/run/haproxy.pid)"
	@echo ""
	@echo "Monitor for 15 minutes. Use 'make go-rollback' if issues appear."

# Rollback: switch HAProxy back to Python proxy.
go-rollback:
	@echo "Rolling back to Python proxy..."
	@echo ""
	@echo "Restore your HAProxy config to:"
	@echo "  backend ja4proxy"
	@echo "      server python-proxy ja4proxy:8080 check"
	@echo ""
	@echo "Then reload HAProxy:"
	@echo "  docker exec haproxy haproxy -sf \$$(cat /var/run/haproxy.pid)"
	@echo ""
	@echo "Rollback complete. Python proxy is primary."

# Run cross-language parity tests.
# Both proxies must be running: Python on :8080, Go on :8082.
go-parity:
	python3 -m pytest tests/integration/test_go_python_parity.py -v

# ── Docker test harness ────────────────────────────────────────────────────────

# Generate ClientHello fixtures (curl + openssl + synthetic)
capture-fixtures:
	@bash scripts/generate_fixtures.sh

# Build ja4check utility (reads .bin file, prints JA4 fingerprint)
go-build-ja4check:
	@echo "Building ja4check..."
	@mkdir -p bin
	$(GO) build -o bin/ja4check ./cmd/ja4check
	@echo "✓ bin/ja4check"

# Run Go integration tests inside Docker (full test harness, self-contained)
test-go-docker:
	@echo "Starting Go proxy test stack..."
	docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from test-runner test-runner

# Run Go integration tests locally (requires Go proxy running on GO_PROXY_PORT)
test-go-integration:
	python3 -m pytest tests/integration/test_go_python_parity.py -v

# Run Go chaos tests locally (requires Go proxy running on GO_PROXY_PORT)
test-go-chaos:
	python3 -m pytest tests/chaos/test_go_proxy_chaos.py -v

# Run Go performance benchmarks locally (requires Go proxy running on GO_PROXY_PORT)
test-go-perf:
	python3 -m pytest tests/performance/test_bench_go_proxy.py -v -s

# Run all Go tests: build binaries, generate fixtures, then run test suite
test-go:
	$(MAKE) go-build
	$(MAKE) go-build-ja4check
	$(MAKE) capture-fixtures
	python3 -m pytest \
	  tests/integration/test_go_python_parity.py \
	  tests/chaos/test_go_proxy_chaos.py \
	  tests/performance/test_bench_go_proxy.py \
	  -v --tb=short

# Capture browser-specific ClientHello fixtures (requires Docker + recorder service)
capture-fixtures-browser:
	docker compose -f docker-compose.test.yml run --rm browser \
	  python3 scripts/generate_fixtures_browser.py --recorder-host recorder
