#!/bin/bash
# JA4 Proxy POC Startup Script
# Starts all services and verifies they are working

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "=========================================="
echo "JA4 Proxy POC Environment"
echo "=========================================="
echo ""

# Check if Docker is running
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}Error: Docker is not running${NC}"
    exit 1
fi

# Auto-generate .env with strong secrets if it doesn't exist
if [ ! -f .env ]; then
    echo -e "${YELLOW}▶ No .env file found — generating with secure defaults...${NC}"
    REDIS_PW=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    GRAFANA_PW=$(openssl rand -base64 24 | tr -d '/+=' | head -c 16)
    cat > .env << EOF
# Auto-generated by start-poc.sh — $(date -Iseconds)
REDIS_PASSWORD=${REDIS_PW}
GRAFANA_PASSWORD=${GRAFANA_PW}
ENVIRONMENT=development
EOF
    chmod 600 .env
    echo -e "${GREEN}  ✓ .env created (chmod 600)${NC}"
    echo -e "  Redis password: ${REDIS_PW}"
    echo -e "  Grafana password: ${GRAFANA_PW}"
    echo ""
fi

# Source .env for use in this script
set -a; source .env; set +a

echo -e "${BLUE}Starting services...${NC}"

# Workaround for Docker iptables issue - try to clean up first
docker network prune -f > /dev/null 2>&1 || true

# Try to start services with --remove-orphans to avoid warnings
if ! docker compose -f docker-compose.poc.yml up -d --remove-orphans redis backend proxy haproxy tarpit 2>&1; then
    echo ""
    echo -e "${RED}Failed to start services. This may be a Docker networking issue.${NC}"
    echo ""
    echo "Try these fixes:"
    echo "  1. Restart Docker daemon: sudo systemctl restart docker"
    echo "  2. Or: sudo service docker restart"
    echo "  3. Then run this script again"
    echo ""
    echo "If the problem persists, check Docker logs:"
    echo "  sudo journalctl -u docker -n 50"
    exit 1
fi

echo ""
echo "Waiting for services to be ready..."
sleep 5

# Check Redis (use password from env)
echo -n "Checking Redis... "
MAX_RETRIES=30
RETRY_COUNT=0
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if docker exec ja4proxy-redis redis-cli -a "${REDIS_PASSWORD}" ping > /dev/null 2>&1; then
        echo -e "${GREEN}✓${NC}"
        break
    fi
    RETRY_COUNT=$((RETRY_COUNT + 1))
    sleep 1
done
if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    echo -e "${RED}✗ Failed${NC}"
    exit 1
fi

# Check Backend (via docker exec since port may be internal-only)
echo -n "Checking Backend... "
RETRY_COUNT=0
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if docker exec ja4proxy-backend python3 -c "import urllib.request,ssl; urllib.request.urlopen('https://localhost/api/health',context=ssl._create_unverified_context())" > /dev/null 2>&1; then
        echo -e "${GREEN}✓${NC}"
        break
    fi
    RETRY_COUNT=$((RETRY_COUNT + 1))
    sleep 1
done
if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    echo -e "${RED}✗ Failed${NC}"
    exit 1
fi

# Check Proxy
echo -n "Checking Proxy... "
RETRY_COUNT=0
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if curl -sf http://localhost:9090/metrics > /dev/null 2>&1; then
        echo -e "${GREEN}✓${NC}"
        break
    fi
    RETRY_COUNT=$((RETRY_COUNT + 1))
    sleep 1
done
if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    echo -e "${RED}✗ Failed${NC}"
    docker compose -f docker-compose.poc.yml logs proxy
    exit 1
fi



echo ""
echo "=========================================="
echo -e "${GREEN}✓ POC services are running!${NC}"
echo "=========================================="
echo ""
echo "Service URLs:"
echo "  Proxy:       http://localhost:8080"
echo "  Metrics:     http://localhost:9090/metrics"
echo "  Backend:     https://localhost:8443"
echo ""
echo "View logs:"
echo "  docker compose -f docker-compose.poc.yml logs -f"
echo ""
echo "Start monitoring (Prometheus/Grafana):"
echo "  ./start-monitoring.sh"
echo "  or"
echo "  ./start-all.sh  # Starts both POC and monitoring"
echo ""
echo "Stop services:"
echo "  docker compose -f docker-compose.poc.yml down"
echo "=========================================="
