"""
Fingerprint accuracy tests using synthetic packet sequences (Phase 20, Group 13-C).

These tests verify that our fingerprint extractors produce the correct JA4 fingerprint
format from known synthetic inputs. Real-PCAP replay tests require the PCAP corpus
(generated by scripts/generate_test_pcap.py) and are marked xfail if not present.
"""

import pytest
from src.tap.fingerprints.ja4 import extract_ja4
from src.tap.fingerprints.ja4h import extract_ja4h
from src.tap.fingerprints.ja4s import extract_ja4s
from src.tap.fingerprints.ja4t import extract_ja4t_from_syn

from tests.tap.conftest import SyntheticPacketBuilder

# Known fingerprint patterns from synthetic inputs
KNOWN_FINGERPRINTS = {
    "chrome_like": {
        "ciphers": [0x1301, 0x1302, 0x1303, 0x00FF],
        "extensions": [0, 11, 10, 16, 22, 23, 13, 43, 45, 51, 21],
        "sni": "example.com",
        "grease": True,
        "expected_prefix": "t13",  # TLS 1.3
    },
    "nmap_like": {
        "ciphers": [0x1301],
        "extensions": [43],
        "sni": None,
        "grease": False,
        "expected_prefix": "t13",
    },
}


class TestFingerprintAccuracy:
    @pytest.mark.parametrize("name,spec", KNOWN_FINGERPRINTS.items())
    def test_fingerprint_extraction_accuracy(self, name, spec):
        """Verify JA4 fingerprint format from synthetic ClientHello."""
        pkts = (
            SyntheticPacketBuilder()
            .syn("1.2.3.4", 54321, "5.6.7.8", 443)
            .synack()
            .ack()
            .tls_client_hello(
                ciphers=spec["ciphers"],
                extensions=spec["extensions"],
                sni=spec.get("sni"),
                grease=spec.get("grease", False),
            )
            .build()
        )
        data_pkts = [p for p in pkts if p.data]
        assert data_pkts, f"No data packets for {name}"

        result = extract_ja4(data_pkts[0].data)
        assert result is not None, f"JA4 extraction failed for {name}"
        assert result.fingerprint.startswith(spec["expected_prefix"]), (
            f"{name}: expected prefix {spec['expected_prefix']!r}, "
            f"got {result.fingerprint!r}"
        )
        # JA4 format: {proto}{tls_ver}{d}{cipher_count}{alpn}_{cipher_hash}_{ext_hash}
        parts = result.fingerprint.split("_")
        assert (
            len(parts) == 3
        ), f"JA4 must have 3 underscore-separated parts: {result.fingerprint}"
        assert len(parts[1]) == 12, f"Cipher hash must be 12 chars: {parts[1]}"
        assert len(parts[2]) == 12, f"Extension hash must be 12 chars: {parts[2]}"

    def test_ja4t_from_syn_options(self):
        """JA4T format from SYN TCP options."""
        import struct

        opts = struct.pack("!BBH", 2, 4, 1460)  # MSS
        opts += struct.pack("!BB", 4, 2)  # SACK
        opts += b"\x01"  # NOP
        opts += struct.pack("!BBB", 3, 3, 7)  # WSCALE

        result = extract_ja4t_from_syn(opts, window_size=65535)
        assert result is not None
        assert "65535" in result.fingerprint
        assert "1460" in result.fingerprint

    def test_ja4h_from_http_request(self):
        """JA4H format from HTTP/1.1 request."""
        http = (
            b"GET / HTTP/1.1\r\n"
            b"Host: example.com\r\n"
            b"Accept-Language: en-US,en;q=0.9\r\n"
            b"Accept: text/html\r\n"
            b"\r\n"
        )
        result = extract_ja4h(http)
        assert result is not None
        assert result.fingerprint.startswith("ge")  # GE = first 2 chars of GET
        assert "11" in result.fingerprint  # HTTP/1.1

    def test_ja4s_from_server_hello(self):
        """JA4S format from TLS ServerHello."""
        pkts = (
            SyntheticPacketBuilder()
            .syn("1.2.3.4", 54321, "5.6.7.8", 443)
            .synack()
            .ack()
            .tls_client_hello()
            .tls_server_hello(cipher=0x1301, extensions=[43, 51])
            .build()
        )
        server_data_pkts = [p for p in pkts if p.src_ip == "5.6.7.8" and p.data]
        assert server_data_pkts, "No server data packet"

        result = extract_ja4s(server_data_pkts[0].data)
        assert (
            result is not None
        ), "JA4S extraction must succeed on synthetic ServerHello"
        assert result.fingerprint.startswith("s")  # server
        parts = result.fingerprint.split("_")
        assert len(parts) == 3, f"JA4S must have 3 parts: {result.fingerprint}"


class TestPcapCorpus:
    def test_chrome_pcap_produces_t13_fingerprint(self):
        """Chrome-like ClientHello should produce a TLS 1.3 fingerprint."""
        pkts = (
            SyntheticPacketBuilder()
            .syn("1.2.3.4", 54321, "5.6.7.8", 443)
            .synack()
            .ack()
            .tls_client_hello(
                ciphers=[0x1301, 0x1302, 0x1303, 0x00FF],
                extensions=[0, 11, 10, 16, 22, 23, 13, 43, 45, 51, 21],
                sni="google.com",
                grease=True,
            )
            .build()
        )
        data_pkts = [p for p in pkts if p.data]
        assert data_pkts, "No data packets produced by SyntheticPacketBuilder"
        result = extract_ja4(data_pkts[0].data)
        assert result is not None, "JA4 extraction failed for Chrome-like ClientHello"
        assert result.fingerprint.startswith(
            "t13"
        ), f"Chrome-like ClientHello should yield TLS 1.3 fingerprint, got: {result.fingerprint}"
