package wizard

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

// secretEnvKeys are the generated .env keys whose values are secrets and must
// never be printed to stdout or logs. Single source of truth, shared by
// mergeSecrets, the dry-run preview redaction (renderEnvRedacted), and the
// lane re-run secret preservation (mergeEnvPreserveSecrets).
var secretEnvKeys = []string{
	"REDIS_PASSWORD", "REDIS_SIGNING_KEY", "MANAGEMENT_JWT_SECRET",
	"MANAGEMENT_ADMIN_PASSWORD", "GRAFANA_PASSWORD", "HAPROXY_STATS_PASSWORD",
	"ANALYTICS_REDIS_PASSWORD", "JA4TAP_REDIS_PASSWORD",
}

// isSecretEnvKey reports whether k is one of the statically-known secret keys.
func isSecretEnvKey(k string) bool {
	for _, s := range secretEnvKeys {
		if s == k {
			return true
		}
	}
	return false
}

// buildEnv returns the full .env map, including secret values (admin password,
// threat-intel API keys, and generated secrets). The result is safe to write to
// the chmod-600 .env file but must NOT be printed; use renderEnvRedacted for any
// human-visible preview.
func buildEnv(a *Answers) map[string]string {
	env := buildPublicEnv(a)

	// Threat-intel API keys and the admin password are secrets — added here, on
	// the disk-write path only. They are deliberately absent from buildPublicEnv
	// so the dry-run preview is built from a map that never holds them.
	for k, v := range a.TIKeys {
		env[k] = v
	}
	if a.AdminPassword != "" {
		env["MANAGEMENT_ADMIN_PASSWORD"] = a.AdminPassword
	}
	return mergeSecrets(env)
}

// buildPublicEnv returns only the non-secret .env entries. Keeping this free of
// any secret value is load-bearing: renderEnvRedacted renders the preview from
// it, so secret data never flows into the printed string.
func buildPublicEnv(a *Answers) map[string]string {
	env := map[string]string{
		"COMPOSE_PROJECT_NAME":  projectName(a),
		"ENVIRONMENT":           "production",
		"BACKEND_HOST":          a.BackendHost,
		"BACKEND_PORT":          fmt.Sprintf("%d", a.BackendPort),
		"AGENT_BIND_IP":         a.BindIP,
		"MANAGEMENT_ADMIN_USER": a.AdminUser,
		"LOG_LEVEL":             a.LogLevel,
		"HOST_PORT_INGRESS":     fmt.Sprintf("%d", basePort("INGRESS")+laneOffset(a)),
		"HOST_PORT_DIRECT":      fmt.Sprintf("%d", basePort("DIRECT")+laneOffset(a)),
		"HOST_PORT_MANAGEMENT":  fmt.Sprintf("%d", basePort("MANAGEMENT")+laneOffset(a)),
		"HOST_PORT_METRICS":     fmt.Sprintf("%d", basePort("METRICS")+laneOffset(a)),
		"HOST_PORT_PROMETHEUS":  fmt.Sprintf("%d", basePort("PROMETHEUS")+laneOffset(a)),
		"HOST_PORT_GRAFANA":     fmt.Sprintf("%d", basePort("GRAFANA")+laneOffset(a)),
	}

	if a.MonitoringStack {
		env["MONITORING_STACK"] = "true"
	}
	if a.Firewall != "" && a.Firewall != "none" {
		env["FIREWALL_BACKEND"] = a.Firewall
	}
	if a.Fail2Ban {
		env["FAIL2BAN_ENABLED"] = "true"
	}
	if a.CrowdSec {
		env["CROWDSEC_ENABLED"] = "true"
	}
	if a.LogForwarding != "" && a.LogForwarding != "none" {
		env["LOG_FORWARDING"] = a.LogForwarding
	}
	if a.DialValue > 0 {
		env["JA4PROXY_DIAL"] = fmt.Sprintf("%d", a.DialValue)
	}
	if a.AllowedSNIs != nil {
		env["ALLOWED_SNIS"] = strings.Join(a.AllowedSNIs, ",")
	}
	if a.UpstreamLB {
		env["UPSTREAM_LB"] = "true"
		if len(a.TrustedCIDRs) > 0 {
			env["UPSTREAM_TRUSTED_CIDRS"] = strings.Join(a.TrustedCIDRs, ",")
		}
	}
	if a.WritePROXY {
		env["WRITE_PROXY_PROTOCOL"] = "true"
		env["WRITE_PROXY_PROTOCOL_VERSION"] = fmt.Sprintf("%d", a.PROXYVersion)
	}
	if a.TLSCerts == "user-supplied" {
		env["TLS_CERT_PATH"] = a.TLSCertPath
		env["TLS_KEY_PATH"] = a.TLSKeyPath
	}

	return env
}

func basePort(name string) int {
	ports := map[string]int{
		"INGRESS":    443,
		"DIRECT":     8081,
		"MANAGEMENT": 8090,
		"METRICS":    9090,
		"PROMETHEUS": 9091,
		"GRAFANA":    3000,
	}
	return ports[name]
}

func laneOffset(a *Answers) int {
	if a.Lane < 0 {
		a.Lane = 0
	}
	return a.Lane * 100
}

func projectName(a *Answers) string {
	if a.LaneName != "" && a.LaneName != "default" {
		return "ja4proxy-" + a.LaneName
	}
	return fmt.Sprintf("ja4proxy-lane%d", a.Lane)
}

func mergeSecrets(env map[string]string) map[string]string {
	for _, k := range secretEnvKeys {
		if _, exists := env[k]; !exists {
			env[k] = genPassword(24)
		}
	}
	if _, exists := env["MANAGEMENT_JWT_SECRET"]; !exists {
		env["MANAGEMENT_JWT_SECRET"] = genHexKey(32)
	}
	if _, exists := env["REDIS_SIGNING_KEY"]; !exists {
		env["REDIS_SIGNING_KEY"] = genHexKey(32)
	}
	return env
}

func renderEnv(env map[string]string) string {
	header := fmt.Sprintf("# Generated by ja4p init (phase-161) — %s", time.Now().Format(time.RFC3339))
	lines := []string{header, "# chmod 600 — contains secrets; never commit."}
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		lines = append(lines, fmt.Sprintf("%s=%s", k, env[k]))
	}
	return strings.Join(lines, "\n") + "\n"
}

// renderEnvRedacted produces a .env preview safe for stdout/logs: every secret
// value is replaced with a fixed placeholder. It is built from buildPublicEnv
// (which holds no secrets) plus placeholder lines keyed only by secret-key NAMES
// — secret values are never read, so no sensitive data flows into the result.
func renderEnvRedacted(a *Answers) string {
	env := buildPublicEnv(a)
	const placeholder = "***REDACTED***"
	for _, k := range secretEnvKeys {
		env[k] = placeholder
	}
	// Threat-intel API keys have dynamic names; redact by key name only.
	for k := range a.TIKeys {
		env[k] = placeholder
	}
	return renderEnv(env)
}

func buildSystemdUnit(a *Answers) string {
	root := "/opt/ja4proxy"
	var start, stop, unitType string
	if a.Mode == "container" {
		start = fmt.Sprintf("/usr/bin/docker compose -f %s/deploy/docker/docker-compose.poc.yml up -d", root)
		stop = fmt.Sprintf("/usr/bin/docker compose -f %s/deploy/docker/docker-compose.poc.yml down -t 30", root)
		unitType = "oneshot\nRemainAfterExit=yes"
	} else {
		start = fmt.Sprintf("%s/bin/ja4pd --config %s/config/proxy.yml", root, root)
		stop = ""
		unitType = "simple"
	}

	lines := []string{
		"[Unit]",
		"Description=JA4proxy (phase-161)",
		"After=network-online.target redis-server.service",
		"Wants=network-online.target",
		"",
		"[Service]",
		"Type=" + unitType,
		"User=ja4proxy",
		"Group=ja4proxy",
		"WorkingDirectory=" + root,
		"ExecStart=" + start,
	}
	if stop != "" {
		lines = append(lines, "ExecStop="+stop)
	}
	lines = append(lines,
		"Restart=on-failure",
		"RestartSec=5",
		"NoNewPrivileges=true",
	)
	if a.Mode != "container" {
		// Native ja4pd runs as the unprivileged ja4proxy user but must bind the
		// public ingress port (e.g. 443). Grant just the bind capability — it
		// survives NoNewPrivileges as an ambient cap — instead of running as root.
		lines = append(lines,
			"AmbientCapabilities=CAP_NET_BIND_SERVICE",
			"CapabilityBoundingSet=CAP_NET_BIND_SERVICE",
		)
	}
	lines = append(lines,
		"",
		"[Install]",
		"WantedBy=multi-user.target",
	)
	return strings.Join(lines, "\n") + "\n"
}

func detectGeoIP() []string {
	paths := []string{
		"/opt/ja4proxy/data/geoip/GeoLite2-ASN.mmdb",
		"/opt/ja4proxy/data/geoip/GeoLite2-City.mmdb",
		"/opt/ja4proxy/data/geoip/GeoLite2-Country.mmdb",
	}
	var found []string
	for _, p := range paths {
		if _, err := os.Stat(p); err == nil {
			found = append(found, p)
		}
	}
	return found
}

func detectGeoIPAt(dir string) []string {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}
	var found []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".mmdb") {
			found = append(found, dir+"/"+e.Name())
		}
	}
	return found
}

func detectFirewall() string {
	for _, fw := range []string{"ufw", "firewalld", "nftables"} {
		path := "/usr/sbin/" + fw
		if _, err := os.Stat(path); err == nil {
			return fw
		}
	}
	return "none"
}
