"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HealthPage = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const useApi_1 = require("../hooks/useApi");
const ui_1 = require("../components/ui");
const lucide_react_1 = require("lucide-react");
const StatusDot = ({ ok }) => ((0, jsx_runtime_1.jsx)("span", { className: `inline-flex h-2 w-2 rounded-full ${ok ? 'bg-green-500' : 'bg-red-500'}` }));
const HealthPage = () => {
    const { data, isLoading, error } = (0, useApi_1.useHealth)();
    const isHealthy = data?.status === 'healthy';
    const redisOk = data?.redis !== false;
    return ((0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col h-full", children: [(0, jsx_runtime_1.jsxs)("div", { className: "mb-4 flex-shrink-0", children: [(0, jsx_runtime_1.jsx)("h1", { className: "text-lg font-semibold text-gray-900", children: "System Health" }), (0, jsx_runtime_1.jsx)("p", { className: "text-xs text-gray-500 mt-0.5", children: isLoading ? 'Checking…' : isHealthy ? 'All systems operational' : 'Degraded — check components below' })] }), error && ((0, jsx_runtime_1.jsxs)(ui_1.Alert, { variant: "destructive", className: "mb-3 flex-shrink-0", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.AlertCircle, { className: "h-4 w-4" }), (0, jsx_runtime_1.jsx)(ui_1.AlertDescription, { children: error.message })] })), (0, jsx_runtime_1.jsx)("div", { className: "flex-1 min-h-0 overflow-y-auto", children: (0, jsx_runtime_1.jsxs)("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4 max-w-2xl", children: [(0, jsx_runtime_1.jsx)("div", { className: "bg-white rounded-lg border border-gray-200 p-4 md:col-span-2", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-3", children: [(0, jsx_runtime_1.jsx)("div", { className: `p-2 rounded-lg ${isHealthy ? 'bg-green-50' : 'bg-red-50'}`, children: isHealthy
                                                    ? (0, jsx_runtime_1.jsx)(lucide_react_1.CheckCircle, { className: "h-5 w-5 text-green-600" })
                                                    : (0, jsx_runtime_1.jsx)(lucide_react_1.XCircle, { className: "h-5 w-5 text-red-600" }) }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("p", { className: "text-sm font-medium text-gray-900", children: "Overall Status" }), (0, jsx_runtime_1.jsx)("p", { className: `text-xs font-semibold ${isHealthy ? 'text-green-600' : 'text-red-600'}`, children: isLoading ? 'Checking…' : data?.status ?? 'unknown' })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "text-right", children: [(0, jsx_runtime_1.jsx)("p", { className: "text-xs text-gray-400", children: "Version" }), (0, jsx_runtime_1.jsx)("p", { className: "text-xs font-mono text-gray-600", children: data?.version ?? '—' })] })] }) }), (0, jsx_runtime_1.jsx)("div", { className: "bg-white rounded-lg border border-gray-200 p-4", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-3", children: [(0, jsx_runtime_1.jsx)("div", { className: `p-2 rounded-lg ${redisOk ? 'bg-green-50' : 'bg-red-50'}`, children: (0, jsx_runtime_1.jsx)(lucide_react_1.Database, { className: `h-4 w-4 ${redisOk ? 'text-green-600' : 'text-red-600'}` }) }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("p", { className: "text-sm font-medium text-gray-900", children: "Redis" }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-1.5 mt-0.5", children: [(0, jsx_runtime_1.jsx)(StatusDot, { ok: redisOk }), (0, jsx_runtime_1.jsx)("p", { className: `text-xs ${redisOk ? 'text-green-600' : 'text-red-600'}`, children: redisOk ? 'Connected' : 'Disconnected' })] })] })] }) }), (0, jsx_runtime_1.jsx)("div", { className: "bg-white rounded-lg border border-gray-200 p-4", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-3", children: [(0, jsx_runtime_1.jsx)("div", { className: "p-2 rounded-lg bg-blue-50", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Clock, { className: "h-4 w-4 text-blue-600" }) }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("p", { className: "text-sm font-medium text-gray-900", children: "Uptime" }), (0, jsx_runtime_1.jsx)("p", { className: "text-xs text-gray-500 mt-0.5", children: data?.uptime != null
                                                    ? `${Math.floor(data.uptime / 3600)}h ${Math.floor((data.uptime % 3600) / 60)}m`
                                                    : '—' })] })] }) }), (0, jsx_runtime_1.jsx)("div", { className: "bg-white rounded-lg border border-gray-200 p-4", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-3", children: [(0, jsx_runtime_1.jsx)("div", { className: "p-2 rounded-lg bg-green-50", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Server, { className: "h-4 w-4 text-green-600" }) }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("p", { className: "text-sm font-medium text-gray-900", children: "Management API" }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-1.5 mt-0.5", children: [(0, jsx_runtime_1.jsx)(StatusDot, { ok: true }), (0, jsx_runtime_1.jsx)("p", { className: "text-xs text-green-600", children: "Operational" })] })] })] }) }), (0, jsx_runtime_1.jsx)("div", { className: "bg-white rounded-lg border border-gray-200 p-4", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-3", children: [(0, jsx_runtime_1.jsx)("div", { className: "p-2 rounded-lg bg-purple-50", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Shield, { className: "h-4 w-4 text-purple-600" }) }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("p", { className: "text-sm font-medium text-gray-900", children: "Proxy Engine" }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-1.5 mt-0.5", children: [(0, jsx_runtime_1.jsx)(StatusDot, { ok: redisOk }), (0, jsx_runtime_1.jsx)("p", { className: `text-xs ${redisOk ? 'text-green-600' : 'text-yellow-600'}`, children: redisOk ? 'Active' : 'Degraded' })] })] })] }) })] }) })] }));
};
exports.HealthPage = HealthPage;
