{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ja4proxy
  labels:
    app: ja4proxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ja4proxy
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: ja4proxy_connections_active
      target:
        type: AverageValue
        averageValue: {{ .Values.hpa.targetConnectionCount }}
{{- end }}
