user default on >5gvCnDqttTQUAVnwk7iWBppAqsKBgcax ~* +@all -@admin
user management on >3FrJRG5MSql5YbCq8JRiag== ~* +@read +@write -@admin
user analytics on >nqcIik7PGzGuX3I0wkE8X9IPWOaNOXmh resetkeys ~analytics:* +@read +@write +ping -@admin
