#!/usr/bin/env python3
"""Detect optimal parallel worker count for this machine.

Runs a small benchmark (one fast unit test module) to measure how quickly
this machine processes tests, then stores the result in .local/machine.mk
for use by the Makefile and run-local-tests.sh.

Usage:
    python3 scripts/detect_workers.py          # detect and store
    python3 scripts/detect_workers.py --show   # print stored config
"""

import os
import subprocess
import sys
import time
from pathlib import Path

LOCAL_DIR = Path(".local")
CONFIG_FILE = LOCAL_DIR / "machine.mk"
SAMPLE_MODULE = "tests/unit/test_risk_scorer.py"


def detect() -> dict:
    ncpus = os.cpu_count() or 4

    print(f"  CPUs detected:  {ncpus}")
    print(f"  Benchmarking with {SAMPLE_MODULE} ...", flush=True)

    start = time.monotonic()
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "pytest",
            SAMPLE_MODULE,
            "-q",
            "--no-header",
            "--tb=no",
            "-p",
            "no:timeout",  # don't apply timeout during calibration
            "--ignore=tests/integration/test_docker_stack.py",
        ],
        capture_output=True,
        timeout=120,
    )
    elapsed = time.monotonic() - start

    # Count tests run (last non-empty line of output)
    out = result.stdout.decode(errors="replace")
    nlines = [ln for ln in out.splitlines() if ln.strip()]
    sample_line = nlines[-1] if nlines else ""

    # Heuristic: on a fast machine (<2s for the sample file), use all cores.
    # On a slow machine (>5s), halve to avoid thrashing.
    if elapsed < 2.0:
        workers = ncpus  # fast — use everything
    elif elapsed < 5.0:
        workers = ncpus  # still fine
    else:
        workers = max(2, ncpus // 2)  # slow — be conservative

    print(f"  Sample time:    {elapsed:.1f}s  ({sample_line})")
    print(f"  → Workers:      {workers}")

    return {"ncpus": ncpus, "elapsed": round(elapsed, 2), "workers": workers}


def write_config(cfg: dict) -> None:
    LOCAL_DIR.mkdir(exist_ok=True)
    CONFIG_FILE.write_text(
        f"# Auto-generated by scripts/detect_workers.py — edit WORKERS to override\n"
        f"# CPU count: {cfg['ncpus']}  |  sample-file time: {cfg['elapsed']}s\n"
        f"# Re-run:  python3 scripts/detect_workers.py\n"
        f"WORKERS := {cfg['workers']}\n"
    )
    print(f"  Stored in:      {CONFIG_FILE}")


def main() -> None:
    if "--show" in sys.argv:
        if CONFIG_FILE.exists():
            print(CONFIG_FILE.read_text(), end="")
        else:
            print(f"No config yet — run: python3 {__file__}", file=sys.stderr)
        return

    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print("  JA4proxy — machine calibration")
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    cfg = detect()
    write_config(cfg)
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")


if __name__ == "__main__":
    main()
