#!/usr/bin/env python3
"""
DEPRECATED — superseded by Phase 161 Go-native ``ja4p init`` wizard.

This Python wizard is retained for reference only. All new deployments
should use ``ja4p init`` (the Go binary) instead, which provides the same
functionality plus full config generation (proxy.yml, haproxy.cfg), lane
isolation, and non-interactive mode.

``bootstrap.sh`` was updated in Phase 332 to call ``ja4p init`` instead of
this script. This file will be removed in a future phase.

---
Original docstring follows:

JA4proxy single-host setup wizard (phase-231b).

Interactively collects deployment choices for a single clean host and writes a
``.env`` (with strong, freshly-generated secrets) plus a systemd unit — so an
operator never hand-edits ``.env``. Designed for a DMZ box that exposes only
443 publicly and points the firewall at JA4proxy for immediate bot relief.

Security (JA4PROXY-2026-0040, mirrored from start-poc.sh): this wizard MUST NEVER
print a secret value. Generated credentials go to ``.env`` (chmod 600) only; the
on-screen summary shows ``[generated — see .env]``.

The pure logic (generation, validation, rendering) is separated from the
interactive prompts so it is unit-testable without driving a TTY.
"""
from __future__ import annotations

import argparse
import ipaddress
import logging
import re
import secrets
import sys
from getpass import getpass
from pathlib import Path
from typing import Callable

logger = logging.getLogger("ja4proxy.setup_wizard")

# Keys whose values are secret and must never be echoed.
SECRET_KEYS: set[str] = {
    "REDIS_PASSWORD",
    "REDIS_SIGNING_KEY",
    "MANAGEMENT_JWT_SECRET",
    "MANAGEMENT_ADMIN_PASSWORD",
    "GRAFANA_PASSWORD",
    "HAPROXY_STATS_PASSWORD",
}

# Published host ports — the real scheme (phase-231a review fix: Management UI is
# 8090, not 8113; metrics 9090; Prometheus 9091; Grafana 3000; no "3023").
# Operators may override; nothing is hard-locked.
DEFAULT_PORTS: dict[str, str] = {
    "HOST_PORT_INGRESS": "443",
    "HOST_PORT_DIRECT": "8081",
    "HOST_PORT_MANAGEMENT": "8090",
    "HOST_PORT_METRICS": "9090",
    "HOST_PORT_PROMETHEUS": "9091",
    "HOST_PORT_GRAFANA": "3000",
}

_HOSTNAME_RE = re.compile(
    r"^(?=.{1,253}$)(?!-)[A-Za-z0-9-]{1,63}(?<!-)(\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))*$"
)


# ── pure helpers (unit-testable) ─────────────────────────────────────────────
def gen_password(nbytes: int = 24) -> str:
    """URL-safe high-entropy password (no shell-hostile characters)."""
    return secrets.token_urlsafe(nbytes)


def gen_hex_key(nbytes: int = 32) -> str:
    """Hex signing key."""
    return secrets.token_hex(nbytes)


def valid_hostname(value: str) -> bool:
    """A DNS hostname or an IP literal is acceptable as a backend target."""
    value = value.strip()
    if not value:
        return False
    try:
        ipaddress.ip_address(value)
        return True
    except ValueError:
        return bool(_HOSTNAME_RE.match(value))


def valid_port(value: str) -> bool:
    try:
        p = int(str(value).strip())
    except (TypeError, ValueError):
        return False
    return 1 <= p <= 65535


def valid_bind_ip(value: str) -> bool:
    try:
        ipaddress.ip_address(value.strip())
        return True
    except ValueError:
        return False


def valid_cert_path(value: str) -> bool:
    return bool(value) and Path(value).expanduser().is_file()


def generate_secrets() -> dict[str, str]:
    """Fresh secrets for every secret key (never reused, never echoed)."""
    return {
        "REDIS_PASSWORD": gen_password(),
        "REDIS_SIGNING_KEY": gen_hex_key(),
        "MANAGEMENT_JWT_SECRET": gen_hex_key(),
        "MANAGEMENT_ADMIN_PASSWORD": gen_password(),
        "GRAFANA_PASSWORD": gen_password(),
        "HAPROXY_STATS_PASSWORD": gen_password(),
    }


def build_env(answers: dict[str, str]) -> dict[str, str]:
    """Merge published-port defaults, operator answers, and fresh secrets into a
    complete ``.env`` mapping. Monitor mode is the safe default (dial handled by
    the proxy config, not here)."""
    env: dict[str, str] = {
        "COMPOSE_PROJECT_NAME": answers.get("project_name", "ja4proxy"),
        "ENVIRONMENT": answers.get("environment", "production"),
        "BACKEND_HOST": answers.get("backend_host", "backend"),
        "BACKEND_PORT": answers.get("backend_port", "443"),
        "AGENT_BIND_IP": answers.get("bind_ip", "127.0.0.1"),
        "MANAGEMENT_ADMIN_USER": answers.get("admin_user", "admin"),
    }
    env.update(DEFAULT_PORTS)
    # Operator port overrides (don't lock ports down).
    for k in DEFAULT_PORTS:
        if k in answers and valid_port(answers[k]):
            env[k] = str(answers[k])
    env.update(generate_secrets())
    return env


def render_env(env: dict[str, str], *, timestamp: str = "") -> str:
    """Render the ``.env`` text. ``timestamp`` is injected (not generated) so the
    output is deterministic and resume/test-friendly."""
    header = "# Generated by scripts/setup_wizard.py (phase-231b)"
    if timestamp:
        header += " — " + timestamp
    lines = [header, "# chmod 600 — contains secrets; never commit."]
    for key in sorted(env):
        lines.append("%s=%s" % (key, env[key]))
    return "\n".join(lines) + "\n"


def write_env(path: Path, env: dict[str, str], *, timestamp: str = "") -> None:
    """Write ``.env`` with 0600 permissions. Never logs a secret value."""
    path.write_text(render_env(env, timestamp=timestamp))
    path.chmod(0o600)
    logger.info("wrote %s (%d keys, chmod 600)", path, len(env))


def redacted_summary(env: dict[str, str]) -> str:
    """A printable summary with every secret replaced — safe to echo."""
    lines = []
    for key in sorted(env):
        val = "[generated — see .env]" if key in SECRET_KEYS else env[key]
        lines.append("  %s = %s" % (key, val))
    return "\n".join(lines)


def build_systemd_unit(deploy_root: str, mode: str) -> str:
    """systemd unit text for native-binary or containerized operation."""
    root = deploy_root.rstrip("/")
    if mode == "container":
        start = "/usr/bin/docker compose -f %s/deploy/docker/docker-compose.poc.yml up -d" % root
        stop = "/usr/bin/docker compose -f %s/deploy/docker/docker-compose.poc.yml down -t 30" % root
        unit_type = "oneshot\nRemainAfterExit=yes"
    else:
        start = "%s/bin/ja4pd --config %s/config/proxy.yml" % (root, root)
        stop = ""
        unit_type = "simple"
    lines = [
        "[Unit]",
        "Description=JA4proxy (single-host, phase-231b)",
        "After=network-online.target redis-server.service",
        "Wants=network-online.target",
        "",
        "[Service]",
        "Type=%s" % unit_type,
        "User=ja4proxy",
        "Group=ja4proxy",
        "WorkingDirectory=%s" % root,
        "ExecStart=%s" % start,
    ]
    if stop:
        lines.append("ExecStop=%s" % stop)
    lines += [
        "Restart=on-failure",
        "RestartSec=5",
        "NoNewPrivileges=true",
        "",
        "[Install]",
        "WantedBy=multi-user.target",
    ]
    return "\n".join(lines) + "\n"


# ── interactive layer (I/O injectable for tests) ─────────────────────────────
def _ask(
    prompt: str,
    default: str,
    validate: Callable[[str], bool] | None,
    input_fn: Callable[[str], str],
) -> str:
    while True:
        suffix = " [%s]: " % default if default else ": "
        raw = input_fn(prompt + suffix).strip() or default
        if validate is None or validate(raw):
            return raw
        sys.stderr.write("  invalid value, try again\n")


def collect_answers(
    input_fn: Callable[[str], str] = input,
    getpass_fn: Callable[[str], str] = getpass,
) -> dict[str, str]:
    """Drive the interactive prompts. I/O is injectable so tests can feed
    scripted answers without a TTY."""
    a: dict[str, str] = {}
    # Python TAP node archived (Phase 128). Only inline (ja4pd) topology is available.
    # Go TAP sensor (Phase 316) is a separate future deployment.
    a["topology"] = "inline"
    a["backend_host"] = _ask("Protected backend host", "backend", valid_hostname, input_fn)
    a["backend_port"] = _ask("Protected backend port", "443", valid_port, input_fn)
    a["mode"] = _ask("Deployment mode: native or container", "container",
                     lambda v: v in ("native", "container"), input_fn)
    a["bind_ip"] = _ask("Admin bind IP (loopback recommended)", "127.0.0.1", valid_bind_ip, input_fn)
    a["admin_user"] = _ask("Management UI admin user", "admin", lambda v: bool(v), input_fn)
    # Admin password: read without echo; empty => generate. Never displayed.
    pw = getpass_fn("Management UI admin password (blank = generate): ")
    if pw:
        a["_admin_password_override"] = pw
    return a


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(description="JA4proxy single-host setup wizard")
    parser.add_argument("--env-path", default=".env", help="output .env path")
    parser.add_argument("--systemd-out", default="", help="optional path to write the systemd unit")
    parser.add_argument("--deploy-root", default="/opt/ja4proxy")
    parser.add_argument("--timestamp", default="", help="stamp written into .env header")
    args = parser.parse_args(argv)

    answers = collect_answers()
    env = build_env(answers)
    if answers.get("_admin_password_override"):
        env["MANAGEMENT_ADMIN_PASSWORD"] = answers["_admin_password_override"]

    write_env(Path(args.env_path), env, timestamp=args.timestamp)
    if args.systemd_out:
        Path(args.systemd_out).write_text(build_systemd_unit(args.deploy_root, env_mode(answers)))
        logger.info("wrote systemd unit to %s", args.systemd_out)

    logger.info("Configuration written. Summary (secrets redacted):")
    logger.info("%s", redacted_summary(env))
    return 0


def env_mode(answers: dict[str, str]) -> str:
    return "native" if answers.get("mode") == "native" else "container"


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
