#!/bin/bash
# JA4 Proxy POC Startup Script
# Starts all services and verifies they are working
#
# SECURITY (JA4PROXY-2026-0040): this script must never echo secrets
# (REDIS_PASSWORD, GRAFANA_PASSWORD, JWT secrets, tokens, keys). Credentials
# live in .env and are read by docker compose directly; do not print them.

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "=========================================="
echo "JA4 Proxy POC Environment"
echo "=========================================="
echo ""

# Check if Docker is running
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}Error: Docker is not running${NC}"
    exit 1
fi

# Auto-generate .env with strong secrets if it doesn't exist
#
# Must cover every ${VAR:?...} required by docker-compose.poc.yml, not just
# the ones this script originally shipped with — REDIS_PASSWORD and
# GRAFANA_PASSWORD alone drifted out of sync with the management/analytics
# services' required secrets (MANAGEMENT_JWT_SECRET, MANAGEMENT_ADMIN_USER,
# MANAGEMENT_ADMIN_PASSWORD, ANALYTICS_REDIS_PASSWORD), breaking any
# from-scratch run (e.g. the nightly benchmark workflow) with no local .env.
if [ ! -f .env ]; then
    echo -e "${YELLOW}▶ No .env file found — generating with secure defaults...${NC}"
    REDIS_PW=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    GRAFANA_PW=$(openssl rand -base64 24 | tr -d '/+=' | head -c 16)
    SIGNING_KEY=$(openssl rand -hex 32)
    ANALYTICS_REDIS_PW=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    MGMT_JWT_SECRET=$(openssl rand -hex 32)
    MGMT_ADMIN_PW=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)
    # Phase 813: the redis service's ACL file (config/redis_acl.conf.template)
    # defines four more named users beyond the proxy's own REDIS_PASSWORD --
    # each needs its own distinct, generated password (JA4PROXY-2026-0043:
    # sharing one password across ACL users means a single leak compromises
    # every role).
    MANAGEMENT_REDIS_PW=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    JA4TAP_REDIS_PW=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    EXPORTER_REDIS_PW=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    # phase-826: shared proxy<->analytics event signing secret. Both services
    # must get the SAME value — a mismatch silently discards every event.
    ANALYTICS_HMAC=$(openssl rand -hex 32)
    cat > .env << ENV_EOF
# Auto-generated by start-poc.sh — $(date -Iseconds)
COMPOSE_PROJECT_NAME=ja4proxy
REDIS_PASSWORD=${REDIS_PW}
GRAFANA_PASSWORD=${GRAFANA_PW}
REDIS_SIGNING_KEY=${SIGNING_KEY}
ANALYTICS_REDIS_PASSWORD=${ANALYTICS_REDIS_PW}
MANAGEMENT_REDIS_PASSWORD=${MANAGEMENT_REDIS_PW}
JA4TAP_REDIS_PASSWORD=${JA4TAP_REDIS_PW}
EXPORTER_REDIS_PASSWORD=${EXPORTER_REDIS_PW}
ANALYTICS_HMAC_SECRET=${ANALYTICS_HMAC}
MANAGEMENT_JWT_SECRET=${MGMT_JWT_SECRET}
MANAGEMENT_ADMIN_USER=admin
MANAGEMENT_ADMIN_PASSWORD=${MGMT_ADMIN_PW}
ENVIRONMENT=development
ENV_EOF
    chmod 600 .env
    echo -e "${GREEN}  ✓ .env created (chmod 600)${NC}"
    echo -e "  Redis password:      [generated — see .env]"
    echo -e "  Grafana password:    [generated — see .env]"
    echo -e "  Management admin:    admin / [generated — see .env]"
    echo ""
fi

# phase-310: assign this worktree a collision-free lane (host ports + unique
# COMPOSE_PROJECT_NAME) before sourcing .env. Idempotent — stable across restarts.
bash "$(dirname "$0")/lane-env.sh"

# Source .env for use in this script
set -a; source .env; set +a

# docker-compose.poc.yml's proxy service pins `cpuset: "${AGENT_CPU_SET:-0-15}"`,
# a default written for the phase-310 multi-agent workstation (16 real cores,
# see scripts/agent-env.sh). On a host with fewer cores -- e.g. GitHub Actions'
# 4-core ubuntu-latest runners -- that default requests CPUs that don't exist,
# failing with "Requested CPUs are not available". Only fill it in when unset;
# agent-env.sh pins it explicitly for named multi-agent lanes and must win.
if [ -z "${AGENT_CPU_SET:-}" ]; then
    AGENT_CPU_SET="0-$(($(nproc) - 1))"
    export AGENT_CPU_SET
fi

# docker-compose.poc.yml's redis service takes its ACL users' passwords via
# Docker Compose file secrets (`secrets: redis_password: file: ../secrets/
# redis_password.txt`, plus one file per ACL user -- Phase 813), not env
# vars directly -- a second, separate prerequisite from .env that this
# script's auto-generation above didn't create for any of them, breaking
# every from-scratch run (e.g. the nightly benchmark workflow) with
# "bind source path does not exist". Keep each in sync with whatever .env
# has (freshly generated above, or pre-existing).
#
# JA4PROXY-2026-0040: deliberately not `echo`/`printf "...${VAR}"` here --
# grep the raw line straight out of .env into the secret file so the
# password is never substituted into an echo/printf argument at all.
mkdir -p deploy/secrets
for pair in \
    "REDIS_PASSWORD:redis_password" \
    "MANAGEMENT_REDIS_PASSWORD:management_redis_password" \
    "ANALYTICS_REDIS_PASSWORD:analytics_redis_password" \
    "JA4TAP_REDIS_PASSWORD:ja4tap_redis_password" \
    "EXPORTER_REDIS_PASSWORD:exporter_redis_password"; do
    env_var="${pair%%:*}"
    secret_name="${pair#*:}"
    secret_file="deploy/secrets/${secret_name}.txt"
    if [ ! -f "$secret_file" ]; then
        grep "^${env_var}=" .env | cut -d= -f2- > "$secret_file"
        chmod 600 "$secret_file"
        echo -e "${GREEN}  ✓ ${secret_file} created (chmod 600)${NC}"
    fi
done

# Pre-flight (JA4PROXY-2026-0045): refuse to publish monitoring/management on a
# public interface. Loopback (default, via SSH tunnel) or private IP only.
python3 "$(dirname "$0")/check_bind_address.py" || exit 1

# Ensure the mock-backend TLS cert exists (gitignored; absent on fresh clone).
bash "$(dirname "$0")/generate-backend-cert.sh"

# Use COMPOSE_PROJECT_NAME if set
P_FLAG=""
if [ -n "$COMPOSE_PROJECT_NAME" ]; then
    P_FLAG="-p $COMPOSE_PROJECT_NAME"
    echo -e "  Project Name: ${BLUE}${COMPOSE_PROJECT_NAME}${NC}"
fi

echo -e "${BLUE}Starting services...${NC}"

# Workaround for Docker iptables issue
docker network prune -f > /dev/null 2>&1 || true

# phase-310: the default single-proxy lane does NOT run HAProxy (it is a load
# balancer for *multiple* proxies; a single dev proxy is reached directly on
# HOST_PORT_DIRECT). Opt in with WITH_HAPROXY=1 for the multi-proxy LB test.
# phase: management was missing here, so `make start` never brought up the
# console — the thing the whole management UI exists for. It is defined in
# docker-compose.poc.yml and published on ${HOST_PORT_MANAGEMENT}, but
# nothing started it.
SERVICES="redis backend proxy tarpit analytics management"
[ "${WITH_HAPROXY:-0}" = "1" ] && SERVICES="$SERVICES haproxy"

# Try to start services
if ! docker compose $P_FLAG -f deploy/docker/docker-compose.poc.yml --env-file .env up -d --remove-orphans $SERVICES 2>&1; then
    echo ""
    echo -e "${RED}Failed to start services.${NC}"
    exit 1
fi

echo ""
echo "Waiting for services to be ready..."
sleep 5

MAX_RETRIES=30

# Check Redis
echo -n "Checking Redis... "
RETRY_COUNT=0
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    # Phase 813: authenticate as the "proxy" ACL user, not the default user
    # -- config/redis_acl.conf.template disables default entirely
    # (`user default off nopass ~* -@all`), so any --user-less `-a` auth
    # attempt is rejected regardless of the password's correctness.
    if docker compose $P_FLAG -f deploy/docker/docker-compose.poc.yml --env-file .env exec -T redis redis-cli --user proxy -a "${REDIS_PASSWORD}" --no-auth-warning ping > /dev/null 2>&1; then
        echo -e "${GREEN}✓${NC}"
        break
    fi
    RETRY_COUNT=$((RETRY_COUNT + 1))
    sleep 1
done
if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then echo -e "${RED}✗ Failed${NC}"; exit 1; fi

# Check Backend
echo -n "Checking Backend... "
RETRY_COUNT=0
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if docker compose $P_FLAG -f deploy/docker/docker-compose.poc.yml --env-file .env exec -T backend curl -kf https://localhost:8443/api/health > /dev/null 2>&1; then
        echo -e "${GREEN}✓${NC}"
        break
    fi
    RETRY_COUNT=$((RETRY_COUNT + 1))
    sleep 1
done
if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then echo -e "${RED}✗ Failed${NC}"; exit 1; fi

# Check Proxy (from INSIDE the container to bypass auth issues)
echo -n "Checking Proxy... "
RETRY_COUNT=0
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if docker compose $P_FLAG -f deploy/docker/docker-compose.poc.yml --env-file .env exec -T proxy curl -sf http://localhost:9090/health > /dev/null 2>&1; then
        echo -e "${GREEN}✓${NC}"
        break
    fi
    RETRY_COUNT=$((RETRY_COUNT + 1))
    sleep 1
done
if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    echo -e "${RED}✗ Failed${NC}"
    docker compose $P_FLAG -f deploy/docker/docker-compose.poc.yml --env-file .env logs proxy
    exit 1
fi

echo ""
echo "=========================================="
echo -e "${GREEN}✓ POC services are running!${NC}"
echo "=========================================="
