#!/bin/bash
# JA4 Proxy POC Startup Script
# Starts all services and verifies they are working
#
# SECURITY (JA4PROXY-2026-0040): this script must never echo secrets
# (REDIS_PASSWORD, GRAFANA_PASSWORD, JWT secrets, tokens, keys). Credentials
# live in .env and are read by docker compose directly; do not print them.

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "=========================================="
echo "JA4 Proxy POC Environment"
echo "=========================================="
echo ""

# Check if Docker is running
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}Error: Docker is not running${NC}"
    exit 1
fi

# Auto-generate .env with strong secrets if it doesn't exist
if [ ! -f .env ]; then
    echo -e "${YELLOW}▶ No .env file found — generating with secure defaults...${NC}"
    REDIS_PW=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    GRAFANA_PW=$(openssl rand -base64 24 | tr -d '/+=' | head -c 16)
    SIGNING_KEY=$(openssl rand -hex 32)
    cat > .env << ENV_EOF
# Auto-generated by start-poc.sh — $(date -Iseconds)
COMPOSE_PROJECT_NAME=ja4proxy
REDIS_PASSWORD=${REDIS_PW}
GRAFANA_PASSWORD=${GRAFANA_PW}
REDIS_SIGNING_KEY=${SIGNING_KEY}
ENVIRONMENT=development
ENV_EOF
    chmod 600 .env
    echo -e "${GREEN}  ✓ .env created (chmod 600)${NC}"
    echo -e "  Redis password:   [generated — see .env]"
    echo -e "  Grafana password: [generated — see .env]"
    echo ""
fi

# Source .env for use in this script
set -a; source .env; set +a

# Pre-flight (JA4PROXY-2026-0045): refuse to publish monitoring/management on a
# public interface. Loopback (default, via SSH tunnel) or private IP only.
python3 "$(dirname "$0")/check_bind_address.py" || exit 1

# Ensure the mock-backend TLS cert exists (gitignored; absent on fresh clone).
bash "$(dirname "$0")/generate-backend-cert.sh"

# Use COMPOSE_PROJECT_NAME if set
P_FLAG=""
if [ -n "$COMPOSE_PROJECT_NAME" ]; then
    P_FLAG="-p $COMPOSE_PROJECT_NAME"
    echo -e "  Project Name: ${BLUE}${COMPOSE_PROJECT_NAME}${NC}"
fi

echo -e "${BLUE}Starting services...${NC}"

# Workaround for Docker iptables issue
docker network prune -f > /dev/null 2>&1 || true

# Try to start services
if ! docker compose $P_FLAG -f deploy/docker/docker-compose.poc.yml --env-file .env up -d --remove-orphans redis backend proxy haproxy tarpit analytics 2>&1; then
    echo ""
    echo -e "${RED}Failed to start services.${NC}"
    exit 1
fi

echo ""
echo "Waiting for services to be ready..."
sleep 5

MAX_RETRIES=30

# Check Redis
echo -n "Checking Redis... "
RETRY_COUNT=0
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if docker compose $P_FLAG -f deploy/docker/docker-compose.poc.yml --env-file .env exec -T redis redis-cli -a "${REDIS_PASSWORD}" --no-auth-warning ping > /dev/null 2>&1; then
        echo -e "${GREEN}✓${NC}"
        break
    fi
    RETRY_COUNT=$((RETRY_COUNT + 1))
    sleep 1
done
if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then echo -e "${RED}✗ Failed${NC}"; exit 1; fi

# Check Backend
echo -n "Checking Backend... "
RETRY_COUNT=0
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if docker compose $P_FLAG -f deploy/docker/docker-compose.poc.yml --env-file .env exec -T backend curl -kf https://localhost:443/api/health > /dev/null 2>&1; then
        echo -e "${GREEN}✓${NC}"
        break
    fi
    RETRY_COUNT=$((RETRY_COUNT + 1))
    sleep 1
done
if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then echo -e "${RED}✗ Failed${NC}"; exit 1; fi

# Check Proxy (from INSIDE the container to bypass auth issues)
echo -n "Checking Proxy... "
RETRY_COUNT=0
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if docker compose $P_FLAG -f deploy/docker/docker-compose.poc.yml --env-file .env exec -T proxy curl -sf http://localhost:9090/health > /dev/null 2>&1; then
        echo -e "${GREEN}✓${NC}"
        break
    fi
    RETRY_COUNT=$((RETRY_COUNT + 1))
    sleep 1
done
if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    echo -e "${RED}✗ Failed${NC}"
    docker compose $P_FLAG -f deploy/docker/docker-compose.poc.yml --env-file .env logs proxy
    exit 1
fi

echo ""
echo "=========================================="
echo -e "${GREEN}✓ POC services are running!${NC}"
echo "=========================================="
