#!/usr/bin/env python3
"""
Sync Roadmap Script
Generates TODO.md and PROJECT_STATUS.md from docs/phases/manifest.yaml

Generation functions return strings so check_manifest.py can import and
compare without touching the filesystem.
"""

import os
import sys
from datetime import datetime

import yaml

MANIFEST_PATH = "docs/phases/manifest.yaml"
TODO_PATH = "docs/phases/TODO.md"
STATUS_PATH = "docs/PROJECT_STATUS.md"

# Maps each canonical status value to the TODO.md section it belongs to.
# None  = phase is not shown in TODO.md (work complete or abandoned).
#
# Keep this aligned with ALLOWED_STATUSES in scripts/lint-phases.py.
# If a new status is added there, add it here too — generate_todo() warns
# on stderr for any phase whose status is absent from this map, so silent
# data-loss on future additions is impossible.
TODO_SECTION_MAP: dict = {
    "COMPLETE":    None,          # Not shown — work done
    "CLOSED":      None,          # Not shown — abandoned/superseded
    "CANCELLED":   None,          # Not shown — absorbed into another phase
    "IN_PROGRESS": "in_progress", # → 🟡 Phases In Progress
    "PROPOSED":    "planned",     # → 🔵 Planned & Open Phases
    "DEFERRED":    "planned",     # → 🔵 Planned & Open Phases
}


def _phase_sort_key(phase_id):
    """Sort key that handles mixed int/float/str phase ids (e.g. 86, 88.1, '86h').

    Returns (numeric_part, suffix) so '86h' sorts immediately after 86 and
    before 87, and 88.1 sorts after 88 and before 88.2.
    """
    s = str(phase_id)
    # Split into leading numeric portion and trailing non-numeric suffix.
    i = 0
    while i < len(s) and (s[i].isdigit() or s[i] == "."):
        i += 1
    num_part = s[:i]
    suffix = s[i:]
    try:
        num = float(num_part) if num_part else 0.0
    except ValueError:
        num = 0.0
    return (num, suffix)


def load_manifest():
    with open(MANIFEST_PATH, "r") as f:
        return yaml.safe_load(f)


# Prefix used in manifest action_plan values — strip it so links are relative
# to the docs/phases/ directory where TODO.md lives.
_DOCS_PHASES_PREFIX = "docs/phases/"


def _action_plan_rel(action_plan: str) -> str:
    """Return the action_plan path relative to docs/phases/.

    If the value starts with "docs/phases/" the prefix is stripped, preserving
    any subdirectory (e.g. "archive/PHASE_05.md" stays intact).
    Falls back to os.path.basename() for values that don't use that prefix.
    """
    if action_plan.startswith(_DOCS_PHASES_PREFIX):
        return action_plan[len(_DOCS_PHASES_PREFIX):]
    return os.path.basename(action_plan)


def generate_todo(manifest) -> str:
    """Return the expected TODO.md content as a string."""
    # Validate statuses up front — warn on any value not covered by TODO_SECTION_MAP.
    # This makes future status additions visible rather than silently dropped.
    for phase_id, data in manifest["phases"].items():
        status = data.get("status", "")
        if status not in TODO_SECTION_MAP:
            print(
                f"WARNING: Phase {phase_id} has unrecognised status {status!r} "
                f"(not in {sorted(TODO_SECTION_MAP)}). "
                f"Phase omitted from TODO.md. "
                f"Update TODO_SECTION_MAP in scripts/sync-roadmap.py.",
                file=sys.stderr,
            )

    lines = [
        "<!-- AUTO-GENERATED by scripts/sync-roadmap.py — do not edit directly -->",
        "<!-- To update: edit docs/phases/manifest.yaml then run: make sync -->",
        "",
        "# JA4proxy Phase TODO List",
        "",
        "This document tracks the remaining work for both historical phases (gaps identified post-completion) and upcoming planned phases. Each item links to a detailed, actionable TDD work plan.",
        "",
    ]

    # In Progress
    lines.append("## 🟡 Phases In Progress")
    lines.append("")

    for phase_id, data in manifest["phases"].items():
        if TODO_SECTION_MAP.get(data.get("status")) == "in_progress":
            lines.append(f"### Phase {phase_id} — {data['name']}")
            for gap in data.get("gaps", []):
                lines.append(f"*   **Gap:** {gap}")
            for task in data.get("tasks_remaining", []):
                lines.append(f"*   **Task:** {task}")
            lines.append(f"*   **Status:** **{data['status']}** ({data['summary']})")
            if "action_plan" in data:
                plan_file = _action_plan_rel(data["action_plan"])
                lines.append(f"*   **Action Plan:** [{plan_file}]({plan_file})")
            lines.append("")

    # Planned / Open
    lines.append("---")
    lines.append("")
    lines.append("## 🔵 Planned & Open Phases")
    lines.append("")

    for phase_id in sorted(manifest["phases"].keys(), key=_phase_sort_key):
        data = manifest["phases"][phase_id]
        if TODO_SECTION_MAP.get(data.get("status")) == "planned":
            lines.append(f"### Phase {phase_id} — {data['name']}")
            lines.append(f"*   **Status:** **{data['status']}** ({data['summary']})")
            if "action_plan" in data:
                plan_file = _action_plan_rel(data["action_plan"])
                lines.append(f"*   **Action Plan:** [{plan_file}]({plan_file})")
            lines.append("")

    return "\n".join(lines)


def generate_status(manifest, date_str: str | None = None) -> str:
    """Return the expected PROJECT_STATUS.md content as a string.

    Pass date_str to override today's date (used by check_manifest.py to
    compare without the timestamp causing false positives).
    """
    if date_str is None:
        date_str = datetime.now().strftime("%Y-%m-%d")

    # Find next actionable phase (first that is not COMPLETE, CLOSED, or CANCELLED)
    _done_statuses = {"COMPLETE", "CLOSED", "CANCELLED"}
    next_phase = "N/A"
    for phase_id in sorted(manifest["phases"].keys(), key=_phase_sort_key):
        if manifest["phases"][phase_id]["status"] not in _done_statuses:
            next_phase = f"Phase {phase_id} ({manifest['phases'][phase_id]['name']})"
            break

    lines = [
        "<!-- AUTO-GENERATED by scripts/sync-roadmap.py — do not edit directly -->",
        "<!-- To update: edit docs/phases/manifest.yaml then run: make sync -->",
        "",
        "# JA4 Proxy - Project Status",
        "",
        f"## Current Status: {next_phase} Next",
        "",
        f"**Last Updated:** {date_str}",
        "",
        "## Epics & Roadmap",
        "",
    ]

    for epic in manifest["epics"]:
        lines.append(f"### {epic['name']}")
        lines.append(epic["description"])
        lines.append("")
        lines.append("| Phase | Name | Status | Summary |")
        lines.append("|-------|------|--------|---------|")
        for phase_id in epic["phases"]:
            p = manifest["phases"][phase_id]
            lines.append(f"| {phase_id} | {p['name']} | {p['status']} | {p['summary']} |")
        lines.append("")

    lines.append("## Phase Completion Details")
    lines.append("")
    lines.append("| Phase | Name | Status | Test Coverage | Documentation |")
    lines.append("|-------|------|--------|---------------|---------------|")
    for phase_id in sorted(manifest["phases"].keys(), key=_phase_sort_key):
        p = manifest["phases"][phase_id]
        lines.append(
            f"| {phase_id} | {p['name']} | {p['status']} "
            f"| {p.get('test_coverage', 'N/A')} | {p.get('doc_status', 'N/A')} |"
        )

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Generated automatically from docs/phases/manifest.yaml*")

    return "\n".join(lines)


if __name__ == "__main__":
    manifest = load_manifest()
    with open(TODO_PATH, "w") as f:
        f.write(generate_todo(manifest))
    with open(STATUS_PATH, "w") as f:
        f.write(generate_status(manifest))
    print(f"Successfully synced {TODO_PATH} and {STATUS_PATH} from manifest.")
